### ISSUE TITLE
Storing downloaded episodes on external storage card fails on Android 11

### ISSUE THREAD

**Issue by timothymctim** [podverse/podverse-rn#1004]
When using Android 11, it isn’t possible to use the external storage for downloaded podcasts.

**To Reproduce**
1. Go to 'More…' > 'Settings' > 'Downloads'.
2. Toggle the option 'External storage card for downloads'.
3. You are now prompted to “transfer or delete prior downloads.” Choose either of them (both fail), but let’s say “Transfer.”
4. You get the prompt “Could not select external storage card: Could not create a Podverse folder on external storage card: Directory could not be created.”

**Expected behavior**
Selecting the “External storage card for downloads” option works and podcasts are transferred to the SD-card.

**Smartphone:**
 - OS: Android 11
 - App Version: 4.3.0 for F-Droid

**Additional context**
This feature was implemented in pull request #879 (requested in issue #602). The error message seems to be generated by React Native, see https://github.com/itinance/react-native-fs/issues/923. I’m unfamiliar with React Native, but it seems like a workaround is available.

**Comment by mitchdowney** [comment]
Fix for this should be in v4.16.0
