### ISSUE TITLE
Downloaded episodes will not play in their entirety or hit the sleep timer when in airplane mode

### ISSUE THREAD

**Issue by joshmather-stripe** [podverse/podverse-rn#1005]
**Describe the bug**
Downloaded episodes will not play in their entirety or hit the sleep timer when in airplane mode

**To Reproduce**
1. Download an episode at least 30 minutes long or so.
2. Put your phone in airplane mode
3. Set a sleep timer for say 30 minutes (this may be unnecesary but is the scenario I'm operating with)
4. Press play
5. after about 20 minutes, podverse will stop playing and will not restart until you reconnect/turn off airplane mode

**Expected behavior**
When you have a downloaded episode and you are in airplane mode, you should be able to play the entire episode or hit a sleep timer.

**Smartphone (please complete the following information):**
 - Device: iPhone 11 Pro Max
 - OS: 15.3
 - App Version 4.3.3 build 1352

**Comment by mitchdowney** [comment]
@joshmather-stripe thanks for the detailed bug report. I'll try this scenario this weekend.

**Comment by mitchdowney** [comment]
@joshmather-stripe this might be fixed in v4.12.0. https://github.com/podverse/podverse-rn/pull/1651

**Comment by mitchdowney** [comment]
AFAIK this is fixed, but there are other Android offline listening issues, possibly due to #1611.
