### ISSUE TITLE
Podcast feeds disappear when updating to 4.3.1 through F-Droid

### ISSUE THREAD

**Issue by betsythefc** [podverse/podverse-rn#1010]
**Describe the bug**

**To Reproduce**
1. Update from 4.3.0 to 4.3.1 via F-Droid

Podcast feeds are not syncing from the website. Out of the 20+ I have, only 1 or 2 show up.
Refreshing does not fix it

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy Flip 3 5G
 - OS: Android 12
 - App Version 4.3.1

**Additional context**
Attempted to uninstall and reinstall a previous version to confirm updating caused the issue.

**Comment by betsythefc** [comment]
When I freshly installed 4.3.1, I was unable to sign in with an error that my password is incorrect, but the same password works on 4.3.0.

**Comment by mitchdowney** [comment]
Hi @betsythefc sorry for the trouble...hmm that's a nasty bug indeed. When I go on the F-Droid store I don't even see 4.3.1 as a download option (maybe a caching issue for me?). There have been a barrage of releases though over the past week, and I actually just released 4.3.4 to F-Droid last night. Before diving deep into this, we should probably check if the problem still exists in 4.3.4. I don't know when it will be available through the F-Droid store though...

In the meantime, if you'd like to try 4.3.4 right away, you could download the apk directly from this link. Looks like you'll need an Azure account to download it though...I'm not sure how to share APK files easily. I used to use this site Blackhole.run but looks like that is not working for me anymore :( 

https://dev.azure.com/podverse/_apis/resources/Containers/14520192/app_build?itemPath=app_build%2Fpodverse-fdroid.signed.release.apk

I hope 4.3.4 fixes the issue but if it doesn't please let me know and we'll look into it more.

**Comment by mitchdowney** [comment]
@betsythefc update, it appears our QA release for Podverse somehow got released as version 4.3.1 😫

Podverse for F-Droid will be completely broken for all users until a correct prod version of Podverse is deployed

**Comment by betsythefc** [comment]
I don't have an azure account, so I'll wait for F-Droid to pick up 4.3.4 and hopefully it's the production version. Once I've gotten it, I'll let you know if it's fixed. Thanks for following up!

**Comment by mitchdowney** [comment]
@betsythefc this should now be fixed in 4.3.5 available now on the F-Droid store. Please lmk if you run into any issues with it. Thanks!

**Comment by betsythefc** [comment]
That fixed it, thank you!
