### ISSUE TITLE
Bluetooth skip button to skip 30 seconds instead of to the next podcast

### ISSUE THREAD

**Issue by betsythefc** [podverse/podverse-rn#1028]
**Is your feature request related to a problem? Please describe.**
Allow a configurable option for skipping with bluetooth buttons. Antennapod can skip forward 30 seconds when pressing the skip buttons in my cars bluetooth. The same button moves to the next podcast in Podverse

**Describe the solution you'd like**
I'd like a setting to switch between the skip buttons on bluetooth going to the next podcast, and using the stock skip forward options (default is 30 seconds forward, 10 seconds back)

**Comment by Chris869218** [comment]
Yea, this would be great. Much safer than going to the phone to skip forward/back within an episode.

**Comment by mitchdowney** [comment]
@betsythefc I've found `remote-next` to be nice when a podcast has chapters, because it will skip to the next chapter....maybe we make that a configurable setting though, and set `remote-next` to be time jump by default for all podcasts.

**Comment by betsythefc** [comment]
Whichever is default is fine with me, as long as I can switch it to my use case 😄

**Comment by mitchdowney** [comment]
@betsythefc @Chris869218 I added a toggle for this in 4.4.2...but I didn't have a bluetooth device to properly test what I did. I *think* it should work but please let me know if it doesn't. The toggle for this feature is on the More > Settings > Player screen. 

I submitted the build to Apple, Google, and F-Droid. It usually takes a few days before they accept and publish the release.

Related commit: https://github.com/podverse/podverse-rn/commit/0af3086e94f7689b58042576aae245f2df022b04

**Comment by betsythefc** [comment]
I tested it in 4.4.2 and it works, thank you!
