### ISSUE TITLE
Investigate battery life usage and try to identify improvements

### ISSUE THREAD

**Issue by mitchdowney** [podverse/podverse-rn#1038]
> I'm using Podverse for android from Fdroid, version 4.4.2. Phone is a Sony Xperia 5ii running android 11.
Since i use Podverse  my battery is draining faster even though i only use it for approx 1 hour a day. In Gsam i can see it is still active keeping my phone awake.
 
> Every time it is pointed towards  "com.facebook.react.HeadlessJsTaskService".

**Comment by cen1** [comment]
Battery usage is excessive when in the background to the point where I now need to think about force killing the app before going to sleep. This should get some more attention.

This screenshot is from overnight usage.

<img width="386" alt="Screenshot 2023-03-02 at 09 15 27" src="https://user-images.githubusercontent.com/1158861/222370684-61cea01e-8e96-46f9-bad0-704595e65a73.png">

**Comment by mitchdowney** [comment]
@cen1 someone else just reported excessive battery issues this week. Apparently the app is draining energy, even when a podcast is paused, and the app is in the background?

I should ask the react-native-track-player team if there are any known issues with battery usage. Perhaps the app is still trying to stream audio in the background, even while paused, leading to excessive battery and data usage? Does a downloaded episode loaded in the player overnight make a difference on battery life? It might not, just a theory 🤷‍♂️

I will do some research about battery usage and mobile app development, and see if there are any improvements I can come up with. Maybe there is a rogue interval in our business logic that is draining the battery needlessly? I have no clear ideas yet, but agreed this needs more attention.

**Comment by mitchdowney** [comment]
Trying to ask Podcast Index social if anyone has tips... https://podcastindex.social/@mitch/109974566837350997

**Comment by cen1** [comment]
Correct, battery is drained even when podcast is paused and app is in the background.

**Comment by mitchdowney** [comment]
@cen1 I don't think it will have a meaningful impact, but I'm adding a change in 4.12.5 intended to help with battery life. It removes the chapter and transcript listeners when the app goes into the background.

I tried finding other more meaningful interval usage, but I'm not seeing any. The main one I was concerned about was our "on player progress" interval, but seems to only be running when the app is playing. https://github.com/podverse/podverse-rn/blob/develop/src/services/playerBackgroundTimer.ts#L137

Maybe a networking issue? Sending requests when we don't expect it? Or something in one of the libraries? I unfortunately don't know how to investigate this further...I'll ask around to see if anyone has advice on how to solve this.

**Comment by cen1** [comment]
The fact that "Media server" process is second on the list of battery usage it makes me suspect somehow the audio was still "playing" except it wasn't.

Will happily test the new version and see if I can consistently reproduce the problem.

**Comment by cen1** [comment]
Happy to report that for the past month I did not have a single incident of major battery usage so either it was a one-off thing or something got it fixed.

**Comment by mitchdowney** [comment]
@cen1 oh, that is great news! I did make some changes to our event listeners (to prevent them from continuously running in the background), and we upgraded our audio library which have had battery optimizations with it.

I'm going to close this issue for now, but there's a good chance we'll reopen it if someone reports similar issues.
