### ISSUE TITLE
F-Droid version: Does not inform that downloading with mobile data is disabled, just hangs forever when trying to download

### ISSUE THREAD

**Issue by hamishmb** [podverse/podverse-rn#1092]
**Describe the bug**
If downloading podcasts over mobile data is disabled, the app doesn't inform you of this when you try to download a podcast. Instead, the download just hangs forever with no progress information. Confused me for a while as I had a very weak signal, and I thought it just couldn't get a usable signal.

**To Reproduce**
1. Disable download over mobile data.
2. Disconnect from WiFi and connect to mobile data.
3. Attempt to download a Podcast.
4. Observe issue.

**Expected behavior**
User is informed that downloads are disabled over mobile data in some way. Perhaps a prompt to change the setting, or status information for the current downloads.

**Screenshots**
N/A

**Smartphone (please complete the following information):**
 - Device: Moto G8 Power
 - OS: Android 11
 - App Version: Not sure, but was the latest as of 13 June 2022 - not too old.

**Additional context**
N/A

**Comment by mitchdowney** [comment]
Thanks @hamishmb this is a great bug report. This should be fixable...hopefully within the next 1-2 months.

**Comment by hamishmb** [comment]
I ain to please :)

**Comment by mitchdowney** [comment]
Added an alert that should popup when you attempt to download an episode when you have "wi-fi only" enabled, but you're not connected to wi-fi. This will be in v4.5.14.

![image](https://user-images.githubusercontent.com/2262919/180645891-9286becc-6b68-49c9-af5b-73ce23eb4713.png)

https://github.com/podverse/podverse-rn/commit/9c4c87d2734ca09db7a489712aa83d2fd729c844

**Comment by hamishmb** [comment]
Cheers :)
