### ISSUE TITLE
My Library "Active Downloads" does not resize for numbers with more than two digits.

### ISSUE THREAD

**Issue by andmagdo** [podverse/podverse-rn#1093]
**Describe the bug**
As the title says, the number alongside the "Active Downloads" is shown in a box that does not resize, leading to larger numbers to wrap and become cut off

**To Reproduce**
1. Start the download an abhorrent amount of podcasts (over 100)
2. Click on the "My Library" button
3. See error near the "Active Downloads" button

**Expected behavior**
The Curved box holding the numbers would resize in order to fit the number.

**Screenshots**
![IMG_20220705_115816](https://user-images.githubusercontent.com/62532857/177380090-2a8504c6-dad8-4dfa-a8dd-7b271e581917.jpg)
![IMG_20220705_115053](https://user-images.githubusercontent.com/62532857/177380096-1b5ce9dc-168c-45e2-9101-ae022dc6d695.jpg)

**Smartphone (please complete the following information):**
 - Device: Google Pixel 6
 - OS: Graphene OS (Latest Stable Build)
 - 4.5.10 (F-Droid)

**Comment by mitchdowney** [comment]
@andmagdo ah, I never tested with 3 digits! Thanks for the report. I'll try to fix this soon.

**Comment by mitchdowney** [comment]
@andmagdo fix will be in v4.5.14

![image](https://user-images.githubusercontent.com/2262919/180645129-f6e257dc-c8b1-4501-8150-05d19a4673d6.png)

https://github.com/podverse/podverse-rn/commit/ed0b6d2f7eb3c5ac5e50f1fd9fdbf27f40111de9
