### ISSUE TITLE
Change skip behavior on Bluetooth accessories to skip X seconds instead of current implementation

### ISSUE THREAD

**Issue by eroc1990** [podverse/podverse-rn#1126]
Currently, when pressing the skip forward/skip back buttons on Bluetooth-paired controllers (in my case, a car steering wheel), the skip action skips to the next item in my queue. Every other podcasting app I have used has used those skip forward/back buttons to initiate time skips instead of queue skips.

Is this something that could be adjusted?

**Comment by mitchdowney** [comment]
@eroc1990 there is actually a setting for this under More > Settings > Player. I'll turn it on by default in the next release though.

![image](https://user-images.githubusercontent.com/2262919/182246535-06cc97f4-3105-4021-ab42-4fd8fc946429.png)

**Comment by mitchdowney** [comment]
@eroc1990 made the change. It will be on by default for new users in the next release, but you'll still need to enable it in settings.

https://github.com/podverse/podverse-rn/commit/bb0f8baba2794f71e07e46fed7bd48a3344bad54

**Comment by eroc1990** [comment]
@mitchdowney Totally missed that. Thanks for that!
