### ISSUE TITLE
Add "Mark as played" button to player

### ISSUE THREAD

**Issue by eroc1990** [podverse/podverse-rn#1129]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Currently, users need to navigate to the podcast, find the episode, and mark it as played. Ideally, a user could mark it as played while the podcast is playing, which would set the playback progress to 100% and move on to the next item in queue. 

**Describe alternatives you've considered**
I know it can be done from the show's episode list page, but that feels clunkier than doing it from in the player. 

**Additional context**
N/A

Please feel free to [join our Discord](https://discord.gg/6HkyNKR) and chat with us in the #dev channel if you'd like to work on this.

**Comment by mitchdowney** [comment]
@eroc1990 interesting I never thought of using that in the player. We do have a more button on the player though without many options. It'd be pretty easy to add "Mark as played" there :)

**Comment by eroc1990** [comment]
@mitchdowney that's kind of what I was thinking. It's a good way to bail out of a podcast if you decide you don't want to complete the episode after all but don't want the progress bar to show partial playback. A weird conundrum, I know. But it's that kind of thing that bugs me when I see it on my own library lol.

**Comment by kreonjr** [comment]
@eroc1990 After a discussion with @mitchdowney, we decided to add the button in the player's more actions list, which will mark the episode as played and skip to the next item in the queue, but won't set the progress to the end, because if we marked an episode played manually, we'd like to know where we left off in case we want to re-listen later.

**Comment by eroc1990** [comment]
@kreonjr That makes sense. I guess I was just speaking more from the perspective of how I use Mark as Played. Generally if I use it while listening to a podcast, I've made the decision that I've listened to enough of the podcast and am ready to call it finished, thus why my original enhancement request led in with that.

**Comment by mitchdowney** [comment]
This should be in v4.6.4.

https://github.com/podverse/podverse-rn/pull/1182
