### ISSUE TITLE
Sort subscribed podcasts by descending "last episode release date"

### ISSUE THREAD

**Issue by ChadFarrow** [podverse/podverse-rn#1131]
**Is your feature request related to a problem? No**

**Describe the solution you'd like**
Ability to sort the podcast tab by release date.

**Comment by eroc1990** [comment]
Is that not what the episode tab is for? The Podcast tab shows you all your subscribed podcasts in one place, and within the episode tab you can see your podcasts in order of release. Are you saying there should be a sort option in the Podcast tab that shuffles more recently updated shows to the top (or bottom, depending on your sort order) of the list?

**Comment by ChadFarrow** [comment]
Correct. I think looking at the podcast page in a sorted thumbnail mode makes it quicker and easier to see which podcast have new episodes especially if you subscribe to a lot of podcast. Pocketcast has this option and I remember it being a nice feature, you could also pin podcast to the top so your favorite shows were quicker to get to.

**Comment by mitchdowney** [comment]
@ChadFarrow hey, that's totally doable. We have a `podcast.lastEpisodePubDate` column, and we'd just need to add a filter for Subscribed podcasts where it sorts descending by `lastEpisodePubDate`. It's pretty easy imo, but it might be a month or two before I can get to it.

**Comment by mitchdowney** [comment]
@ChadFarrow @eroc1990 this should be in v4.6.3

![Screen Shot 2022-08-28 at 11 31 52 PM](https://user-images.githubusercontent.com/2262919/187123523-bfeae047-db00-48a9-80ee-991a0afa200e.png)

![Screen Shot 2022-08-28 at 11 32 09 PM](https://user-images.githubusercontent.com/2262919/187123553-4e5dc578-08dc-4295-a9dd-2539629a2e4f.png)

**Comment by eroc1990** [comment]
Awesome, thanks for the addition!

**Comment by ChadFarrow** [comment]
Thanks

**Comment by mitchdowney** [comment]
Deployed in v4.6.3 https://github.com/podverse/podverse-rn/pull/1181
