### ISSUE TITLE
Add ability to sort downloaded episodes on the Podcast Screen by "oldest" sorting

### ISSUE THREAD

**Issue by mitchdowney** [podverse/podverse-rn#1155]

**Comment by stclair77** [comment]
PLEASE!  This is bizarre to me.  Every other podcast app I've used has this feature available.  I switched to Podverse a couple of days ago to support Adam Curry's mission but this is a very frustrating shortcoming.

**Comment by mitchdowney** [comment]
@stclair77 this should be in v4.6.3. https://github.com/podverse/podverse-rn/commit/bd2dade6aaede0e7fa4ca4052623533473125354

Hopefully I didn't introduce any bugs to the PodcastScreen because it's a little complicated 😬

**Comment by stclair77** [comment]
Hey!    No rush at all. I just really appreciate how responsive you guys have been. I love everything else about it, so I’m here to stay no matter what.   
  
  
  
  
  
  
  

  
  
>

**Comment by mitchdowney** [comment]
No problem! This is a great / essential feature request.

Deployed in v4.6.3 https://github.com/podverse/podverse-rn/pull/1181

iOS and Google Play should be available later today.

F-Droid builds take longer and probably won't be available for 1 week.

Closing this issue for now. Will open a new issue if any bugs are introduced.
