### ISSUE TITLE
Custom added RSS Podcasts are constantly disappearing

### ISSUE THREAD

**Issue by mitchdowney** [podverse/podverse-rn#1156]
> OnePlus 6T
> My custom added RSS Podcasts are constantly disappearing. Sometimes they show up again, and then half of them disappear. I've manually added them a few times, subscribed to each one, and enabled auto downloads. Yet they keep disappearing.

**Comment by k4j8** [comment]
I was able to replicate this issue with on two different Android phones using both F-Droid and the Google Play store, version 4.6.2.

**Comment by mitchdowney** [comment]
@k4j8 I'm still unable to reproduce this problem on Google Play or F-Droid :( even when I put the phone in airplane mode it seems to work.

Are there any particular feeds you have noticed this issue with? Are there any patterns you're seeing when you have the issue? Like, could you have weak internet access at the time? The feeds still shouldn't disappear if that's the case...but maybe there's a bug with that situation.

**Comment by k4j8** [comment]
Thanks for looking into this. It's happened on a few different feeds, but they are custom URLs for a paid subscription. It also only happens when other podcasts are present in my library. Loading a custom URL into an empty library works reliably without issue.

I will work on providing you with a minimal list of steps to replicate and see if I can determine which podcasts are problematic.

**Comment by k4j8** [comment]
Thanks for all the work on custom RSS feeds! All of my podcasts added in this way work without issue and display the "RSS" banner at the top of the episode. Great work and thanks again! I recommend closing this issue.

**Comment by mitchdowney** [comment]
@k4j8 woohoo! 🥳 that's great news. Thanks for updating us.

We have big plans for upgrading our custom RSS feature so it has better feature parity with our server-side/non-custom RSS feeds, but we're expecting to do a full rewrite of our database schema and API before we get there, so that may not be for quite a while. If you notice other bugs in meantime please let us know as we want the current custom RSS UX to be as stable as it can be.
