### ISSUE TITLE
"Connect to the internet and try again" error after 4.6.0 update on F-Droid

### ISSUE THREAD

**Issue by eroc1990** [podverse/podverse-rn#1171]
**Describe the bug**
After updating the app, I was logged out. When trying to log back in, I was met with the error text in the title. I've tested this on my home wifi (Spectrum, USA) and Verizon Wireless LTE. Both resulted in the same issue. 

**To Reproduce**
1. Launch app
2. More > Log in
3. Enter credentials and submit 
4. Received error 

**Expected behavior**
My account should be logged in after submitting valid credentials. 

**Screenshots**
![Screenshot_20220818-111541~2.png](https://user-images.githubusercontent.com/13401635/185432982-6af2417e-1965-4e71-8366-5505679842f4.png)

**Smartphone (please complete the following information):**
 - Device: Google Pixel 6a
 - OS: 12, build SD2A.220601.004.B2
 - App Version 4.6.0 F-Droid

**Additional context**

Please feel free to [join our Discord](https://discord.gg/6HkyNKR) and chat with us in the #dev channel if you'd like to work on this.

**Comment by VKEERTHIVIKRAM** [comment]
I had the same issue. I cleared the AppData and then Logged in, and then it worked fine.

**Comment by eroc1990** [comment]
> I had the same issue. I cleared the AppData and then Logged in, and then it worked fine.

That worked for me. Weird that _that's_ what it took to make it work, though. Leaving this open in case there's something underlying that might be causing this issue.

**Comment by eroc1990** [comment]
Nvm closing this. I'm an idiot and opened it in the wrong repo. But thanks for the help anyway @VKEERTHIVIKRAM

**Comment by maxamillion** [comment]
Same issue here updating from the Google Play store.

**Comment by maxamillion** [comment]
I should note that clearing data as noted above did resolve the issue. Thanks!

**Comment by kreonjr** [comment]
Thanks everyone for reporting this issue. We have identified the problem and it is related to the opensource encryption library that we use to store credentials. A ticket already exists on their GitHub and I have reported the issue happening in our app as well. 

It would immensely help if you could provide your device type and operating system version being used as it seems to be an android/fdroid problem only. 

The more data we can provide them with, the quicker I believe they will address the issue.

In the meantime, our next app release we’ll have a more descriptive error that will also attempt to navigate the user to the cache reset settings in case this particular error shows up.

**Comment by mitchdowney** [comment]
Deployed in v4.6.3 https://github.com/podverse/podverse-rn/pull/1181
