### ISSUE TITLE
Broken Podcast feed (Android Only)

### ISSUE THREAD

**Issue by ASNosal** [podverse/podverse-rn#1174]
**Describe the bug**
Playerprofiler podcast does not play or download in Android, but works fine on the web.

**To Reproduce**
1. Subscribe to https://podverse.fm/podcast/ncvuf2xgU
2. Attempt to play or download an episode, but only get errors

**Smartphone (please complete the following information):**
 - Device: Pixel 6
 - OS: [Android 12]
 - App Version 4.6.2

Please feel free to [join our Discord](https://discord.gg/6HkyNKR) and chat with us in the #dev channel if you'd like to work on this.

**Comment by eroc1990** [comment]
I just tested this on F-Droid 4.6.2 fr Android 13 on Pixel 6a. I only tried the latest episode, but that began playing within a couple seconds of pressing play from the show feed page.

**Comment by ASNosal** [comment]
Hmm, you're right. It seems like it's isolated to this episode: https://podverse.fm/episode/Zh6nJRZgaw

**Comment by ASNosal** [comment]
This feed continues to have random episodes that do not play through the Android app, but play fine through the web interface.
