### ISSUE TITLE
Add Value for Value streaming sats support

### ISSUE THREAD

**Issue by mitchdowney** [podverse/podverse-rn#1176]
This is blocked until we update to react-native-track-player v3. 

> no streaming sats in Podverse, basically we need a timer interval that runs during playback *even while the app is in the background*. The v2 version of the audio library we are using doesn’t offer an interval timer we can use that runs in the background

> The good news is they just released v3 of their library with a background interval last week. This should allow us to add streaming sats, improve the reliability of our “sync history with server” feature, and fix our sleep timer

**Comment by mitchdowney** [comment]
Blocked due to https://github.com/podverse/podverse-rn/issues/1179

**Comment by mitchdowney** [comment]
This should be in v4.10.0 #1514

**Comment by genebean** [comment]
I’m on the edge of my seat waiting for that build to drop :) 4.9.0 (1926) is the newest I see at the moment.
