### ISSUE TITLE
Sometimes when I unpause it starts playing from a state that is way earlier from where I paused at.

### ISSUE THREAD

**Issue by xrishox** [podverse/podverse-rn#1211]
**Describe the bug**
I listen to podcasts at work so I regularly need to pause and unpause depending on what is going on. Sometimes when I unpause it starts playing from a point in the podcast that is way earlier than where I was when I paused it. I can't tell if it's an arbitrary point in time or if maybe it is starting from a point that I had paused at earlier in the day or something.

**To Reproduce**
I don't know how to reproduce it consistently since it happens intermittently and seemingly randomly.

**Expected behavior**
I would expect it to pick up from where I paused the audio at.

**Smartphone (please complete the following information):**
 - Device: iPhone 13 Pro Max
 - OS: iOS 15.6.1
 - App Version: 4.6.4 Build 1681

**Additional context**
I always pause and unpause my content while the device is in my pocket using the button on my headphones. I'm not sure if that could have anything to do with it. It seems unlikely but could be relevant.

**Comment by mitchdowney** [comment]
@xrishox are you using Podverse with a logged-in Premium account? This appears to be an issue with the pause / resume function falling out of sync with what is saved on the server. For example, if you play from 15 minutes in, and a network request successfully saves 15:00 to the server, then you press pause at 1 hour in _but that save to server request fails_, then the next time you resume it might pull the last time saved on the server, which was an older time :[

We have a plan to improve the reliability of our save playback position to server feature, but it is currently blocked by #1179 which will be a major update we have to be very careful deploying. Unfortunately this issue may persist until then.

A couple questions for you:

1) Are you using the app as a Premium user?

2) Do you know if you tend to have weaker internet connection in the areas when you see the issue?

**Comment by xrishox** [comment]
I am using a logged in premium account. i'm not aware of it happening when i have a weak connection, but it wouldn't surprise me if i lost connection for 10 seconds here or there.  i don't remember exactly but i'm pretty sure i've also had this bug come up when I am at home on my wifi which should have a pretty rock solid reliable connection. would it be helpful to you if i logged out of the premium account and see if the problem persisted?

**Comment by mitchdowney** [comment]
@xrishox thanks for the offer, but I don't think you need to go through the trouble right now. I think it's much more likely to be related to our history service and the audio player library we use (react-native-track-player).

Currently the app will send "save latest playback time to history" requests on play/pause/interruption events. After we update to RNTP v3.x #1179 we'll be able to send those requests like once per minute. That should hopefully prevent the app from losing your place at least by so much. There's probably more to this bug though and that might just be a mitigation.

**Comment by mitchdowney** [comment]
AFAIK this is fixed.
