### ISSUE TITLE
Add iPad and Android tablet support

### ISSUE THREAD

**Issue by mitchdowney** [podverse/podverse-rn#1215]
Currently Podverse is intended for mobile devices only. It'd be nice to add tablet support for iOS and Android as well.

If possible, it would be nice to enable landscape mode for tablets only.

**Comment by mitchdowney** [comment]
#1425 
#1426

**Comment by mitchdowney** [comment]
Duplicate of https://github.com/podverse/podverse-rn/issues/889

**Comment by mitchdowney** [comment]
This should be in v4.7.0

**Comment by suorcd** [comment]
Full screen looks good.

The split screen and floating views don’t reflow. 
![Add iPad and Android tablet support · Issue #1215 · podversepodverse-rn](https://user-images.githubusercontent.com/60907848/202352984-8acf893b-f7cc-4e88-a1f2-df4429dd77d4.png)
