### ISSUE TITLE
Hide played episodes should come with "mark all as played"

### ISSUE THREAD

**Issue by freekvh** [podverse/podverse-rn#1241]
**Is your feature request related to a problem? Please describe.**
I would prefer to not see played episodes of a podcast in the feed's overview, that way it becomes very easy to see what episode you still have to listen to.

**Describe the solution you'd like**
A button that says: "Hide played episodes from feed list".

**Comment by freekvh** [comment]
Ok, I see that this is available in the filter button as "Hide completed" how ever, in this case it must come with a "mark all as played" button, because now the feed simply displays all episode I have not listen to but are very old and no longer relevant,

**Comment by mitchdowney** [comment]
@freekvh thanks for creating this. There's actually an existing open issue for this #935, so I'm going to mark this as a duplicate and close it.
