### ISSUE TITLE
Add indicator to custom RSS feed podcasts

### ISSUE THREAD

**Issue by genebean** [podverse/podverse-rn#1244]
**Is your feature request related to a problem? Please describe.**

There currently doesn’t seem to be any way to determine if a podcast has been added via a custom rss feed. This is problematic because some features don’t work on custom feeds. 

**Describe the solution you'd like**

Fountain solved this by adding a little note below the show art. Maybe Podverse could do something equally as clear, even if not the same solution. Below is an example of what Fountain does. 

![E384CFA4-1A65-4367-BEC2-29AB50A4C708](https://user-images.githubusercontent.com/966789/191319286-8b688f1c-fe45-4406-b92f-68e7318aa927.jpeg)

**Describe alternatives you've considered**

Small, nondescript icons - these would likely not convey the info as well to a user as they’d have to first figure out what the icon is for.

**Comment by mitchdowney** [comment]
@genebean this should be in the next 4.6.7-prod.2 release #1252

![image](https://user-images.githubusercontent.com/2262919/191857495-83a551e3-4180-438f-8bce-9209c59017b8.png)

![image](https://user-images.githubusercontent.com/2262919/191857513-680eedfc-8686-4b89-a98e-064a49539e2e.png)
