### ISSUE TITLE
Google Play rejection: "Your offer does not clearly and accurately describe the terms of your subscription..."

### ISSUE THREAD

**Issue by mitchdowney** [podverse/podverse-rn#1248]
We received a rejection on our latest build to Google Play with the following explanation:

> Your offer does not clearly and accurately describe the terms of your subscription, including the cost, frequency of billing cycle, and whether a subscription is required to use the app.

![com podverse-InAppExperience-271 (1)](https://user-images.githubusercontent.com/2262919/191635516-a571057b-8c3f-4f05-8fd5-14e10a7d748b.png)

The description doesn't explain exactly what needs to change beyond that...

**Comment by mitchdowney** [comment]
Should be in 4.6.7-prod.2 #1249

**Comment by comradekingu** [comment]
@mitchdowney 
There are two competing interests there, what Google thinks, and what the audience understands.
Selling memberships by focusing on how both much one gets for free, and invoking price isn't a winning move.
How about "included".
I know a bit about how Google does things. What is the hold-up currently?

Also, "Renew" for specifically currently active subscriptions might create uncertainty. How about "Prolong" or something similar?

**Comment by mitchdowney** [comment]
There are about 10 other fixes that we need to get out to beta and hopefully prod soon, so I'm going with "Free" and "Renew" for now. "Renew" is definitely the more common convention in US English for "renewing" a membership or paid subscription. It's also commonly understood that a customer can have a "free membership" or a "paid membership", so we're erroring on the side of "Free" for this next Google Play review.

I wonder if changing the key names in the base language json file for words with fuzzy meaning would help? Basically the key could express some context about the words meaning in English? So in the base file that would look like `"At no cost": "Free"`.

While there is the translations-context.md, I don't expect most translators to even know that exists...it would be very very easy to make the key changes, and retain the existing translations across languages.

If you'd like to discuss changing "Free" or "Renew" in the base language, please open a new Github issue for it. There is a "translations" issue tag we could assign to discussions like this. Thanks again for your help 🙏
