### ISSUE TITLE
Remember filter settings on episodes screen

### ISSUE THREAD

**Issue by genebean** [podverse/podverse-rn#1268]
**Is your feature request related to a problem? Please describe.**

i hate having to reset my filter to download led from subscribed every time I go into the episodes screen.

**Describe the solution you'd like**

I want the app to remember what my filter was set to the last time I used the app. 

**Describe alternatives you've considered**

Allow customizing the default filter in preferences.

**Comment by mitchdowney** [comment]
Great idea @genebean. I'll try to get this in the next release within the next 1-2 weeks.

**Comment by mitchdowney** [comment]
@genebean 

This should be in v4.6.9 #1302 

![CleanShot 2022-10-03 at 18 56 08](https://user-images.githubusercontent.com/2262919/193706448-124369e6-6dad-462c-95e7-2349f31477fc.gif)
