### ISSUE TITLE
Make transcripts visible without playing episode 

### ISSUE THREAD

**Issue by genebean** [podverse/podverse-rn#1342]
It seems transcripts only show when an episode is played. Many times I’d like to reference a transcript without having to play an episode.

**Comment by mitchdowney** [comment]
I really like this idea. We could add it to the Episode screen along side the "Chapters" and "Clips" list items.

**Comment by mitchdowney** [comment]
@genebean this should be in v4.6.12

![image](https://user-images.githubusercontent.com/2262919/199890415-88a880b0-4174-4516-9a8b-f7a12e690f9e.png)

![image](https://user-images.githubusercontent.com/2262919/199890431-a20b10ac-4114-4fbc-9a13-d2a116601498.png)
