### ISSUE TITLE
Add handling to import OPML directly from other apps into Podverse mobile

### ISSUE THREAD

**Issue by mitchdowney** [podverse/podverse-rn#1385]
> 1. when exporting opml from another app Podverse doesn't present itself as a handler for that file type. Workaround I used was to save it to files and fetch it from within the app.

I didn't realize this is even possible. If anyone has input or links that can help explain how we can set this up for iOS and/or Android I'd really appreciate it.

**Comment by DacoDev** [comment]
Another podcast app I've used recently called Snipd has that as an option, and when I was importing from PocketCasts, that was the only option they gave for importing. Looking at the other app options it's the same process of creating export, and target Snipd.

I think this is relevant: https://stackoverflow.com/questions/31426174/ios-import-file-from-another-app-into-my-app

Where you'd need to have Podverse available as a target to share to; I'm not an iOS dev so I don't know if that's correct or on the right path but seemed possible!

![D87960B8-7C05-437A-9405-608C7C02D8F7](https://user-images.githubusercontent.com/20329637/199648688-4516cfcf-885b-4f16-833a-7418c3cb5ba9.png)

**Comment by mitchdowney** [comment]
This is partially in https://github.com/podverse/podverse-rn/commit/9bccbcdd21a094e8f54345c704135720e3a652f8

But not completed yet. Unsure if it will be in v4.6.12 or not.

**Comment by mitchdowney** [comment]
This should be in v4.6.12 thanks to @kreonjr #1403
