### ISSUE TITLE
OMPL filename with space fails to import.

### ISSUE THREAD

**Issue by DacoDev** [podverse/podverse-rn#1388]
**Describe the bug**
When importing an OMPL, if there is a space in the filename it will fail to import.

**To Reproduce**
Attempt to import an OMPL with a space in the filename. In my case it was called "podcasts 2.ompl" since I already had a "podcasts.ompl" in the same folder.

**Expected behavior**
Import the OMPL with no modifications needed.

**Screenshots**

![679EC04F-9A0C-4A6C-A47B-4120EF07412F](https://user-images.githubusercontent.com/20329637/199649623-58db198b-4d9e-4b64-adb8-f88120a26e7f.png)

**Smartphone (please complete the following information):**
 - Device: iPhone 13
 - OS: iOS 16.0.2
 - App Version: 4.6.11 B1795

**Additional context**
Removing the space from the file allowed it to import as expected.

**Comment by mitchdowney** [comment]
This should be in v4.6.12

https://github.com/podverse/podverse-rn/commit/9bccbcdd21a094e8f54345c704135720e3a652f8

**Comment by DacoDev** [comment]
Awesome, thank you!
