### ISSUE TITLE
Testflight split view issues

### ISSUE THREAD

**Issue by suorcd** [podverse/podverse-rn#1450]
**Describe the bug**
The pane size does not resize to current window size.

**To Reproduce**
put Podverse into split view
use player or show tile view in pod cast

**Expected behavior**
Re-sizing of elements to fit pane

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: iPad Pro 12.9
 - OS: 16.1
 - App Version 4.7.0 (1854)
 
**Additional context**
Same behavior in when using a non-floating split screen

Please feel free to [join our Discord](https://discord.gg/6HkyNKR) and chat with us in the #dev channel if you'd like to work on this.

**Comment by mitchdowney** [comment]
Should be in v4.7.1

![image](https://user-images.githubusercontent.com/2262919/204074208-cf5eb957-fc70-43ac-8344-91a700ffeb64.png)
