### ISSUE TITLE
Change behavior for swipe actions on podcast

### ISSUE THREAD

**Issue by rastacalavera** [podverse/podverse-rn#1466]
**Is your feature request related to a problem? Please describe.**
Currently when looking at the list of subscribed podcasts in the app, when the user swipes from right to left, the option to unsubscribe appears. 

**Describe the solution you'd like**
I think that instead of unsubscribing, the action of swiping from right to left should give you the option to clear episode count or mark all as played.

**Additional context**
![swipe](https://user-images.githubusercontent.com/6867792/205139937-899ebf53-1c62-45cf-8795-19da9202c42a.png)

**Comment by mitchdowney** [comment]
Should be in v4.8.0 #1470 

![image](https://user-images.githubusercontent.com/2262919/205463484-daabc449-013f-458e-8ba7-a7069261e850.png)
