### ISSUE TITLE
Podcast is downloaded automatically even if marked as played 

### ISSUE THREAD

**Issue by genebean** [podverse/podverse-rn#1519]
**Describe the bug**

Podcast is downloaded automatically even if marked as played 

**To Reproduce**
1. Go to a podcast that’s not already automatically downloaded 
2. Mark most recent episode as played
3. Toggle on auto download 
4. Watch played episode download 

**Expected behavior**

I expect episodes marked as played to not automatically download 

**Smartphone (please complete the following information):**
 - Device: iPhone 12
 - OS: 16.1.1
 - App Version 4.10.0 build 1933

**Comment by mitchdowney** [comment]
@genebean I'll try to get this in the next release.

**Comment by genebean** [comment]
Awesome

**Comment by mitchdowney** [comment]
This should be in v4.10.2

**Comment by genebean** [comment]
Awesome!
