### ISSUE TITLE
Last played podcast should be removed from Now Playing after the end is reached and the app closed

### ISSUE THREAD

**Issue by mitchdowney** [podverse/podverse-rn#1526]
> Hey guys lots of great updates to the stability of the Android app in the last couple of releases.  One thing that still bugs me is that the player  still shows the last podcast played even though it was listened to.  For  example this morning I listened to a podcast and then when I go back to the app it's still showing at the bottom of the screen.  Other podcast apps will clear that area when the podcast is finished.  See picture attached , Mark Levin's podcast still shows active in the player even though I finished listening to it.

**Comment by genebean** [comment]
I’ve noticed this on iOS some too

**Comment by mitchdowney** [comment]
There are some bugs / quirks with react-native-track-player v2 that are causing this to be difficult to implement. I'm going to mark this as blocked until we update to RNTP v3. #1179

**Comment by mitchdowney** [comment]
AFAIK this is fixed.
