### ISSUE TITLE
Playback continues when car turns off

### ISSUE THREAD

**Issue by genebean** [podverse/podverse-rn#1542]
**Describe the bug**

Multiple times since starting to use the new CarPlay feature, when I turn the car off OR simply unplug my phone, playback continues. In all other apps either of these would cause playback to stop. 

**Expected behavior**

Playback should stop when the car is turned off or the phone is unplugged. 

**Smartphone (please complete the following information):**
 - Device: iPhone 12
 - OS: iOS 16.1.1
 - App Version 4.10.0 build 1940

**Additional context**

Please feel free to [join our Discord](https://discord.gg/6HkyNKR) and chat with us in the #dev channel if you'd like to work on this.

**Comment by mitchdowney** [comment]
@genebean thanks for the bug report. This might be very easy and I'll try to get it in next release 4.10.2.

**Comment by mitchdowney** [comment]
@genebean code pushed. This should be in v4.10.2

**Comment by genebean** [comment]
Awesome
