### ISSUE TITLE
Comments don’t scroll 

### ISSUE THREAD

**Issue by genebean** [podverse/podverse-rn#1544]
**Describe the bug**
The comments don’t scroll for me. 

https://user-images.githubusercontent.com/966789/209419055-ad0eb2cd-f758-4ccc-ad85-1660d0118413.MOV

**Smartphone (please complete the following information):**
 - Device: iPhone 12
 - OS: iOS 16.1.1
 - App Version 4.10.1 build 1945

**Comment by illumiN8i** [comment]
Same here on Android.

**Comment by mitchdowney** [comment]
@genebean @illumiN8i thanks for the bug reports. I missed this as the issue apparently doesn't happen on iOS, but does on Android. Should be fixed in the next release.

**Comment by genebean** [comment]
It does happen on iOS @mitchdowney

**Comment by mitchdowney** [comment]
This should be fixed in v4.10.2
