### ISSUE TITLE
Improve episode download resume functionality for unreliable internet connections

### ISSUE THREAD

**Issue by mitchdowney** [podverse/podverse-rn#1551]
Make the episode downloads resume successfully even if the connection throws an error, or internet connection is lost, or times out.

> How to debug from the US? First make sure your router is within arm's reach. Then, periodically throughout the day unplug your router for some randomly variable number of minutes. Bonus points if you sometimes leave it unplugged for several hours, even for the whole day. You are now emulating international bandwidth behind the G.Firewall.

More info: https://freeradical.zone/@udzsigfwzw/109578914840213198

**Comment by DocDoo** [comment]
Hi @mitchdowney 
When downloads (album art and episode downloads) fail is the visual cues for this then the same as what I see in the two screenshots below (Podverse on Android) or are these indicators or another issue?
![Screenshot_20230207-072927_Podverse](https://user-images.githubusercontent.com/46087270/219021129-8cebe654-9b3f-4601-ab16-00b1d7be9765.jpg)
![Screenshot_20230215-084059_Podverse](https://user-images.githubusercontent.com/46087270/219021132-17b0c1ca-f292-43f9-9014-49e79589e0c4.jpg)

**Comment by mitchdowney** [comment]
@DocDoo those two issues you are seeing are actually different than the "download resume" functionality in this Github issue.

Screenshot 1: was this a downloaded episode? Or a streamed episode? If downloaded, then unfortunately I'm pretty stumped what is going wrong, but I'm hoping fixing #1611 will resolve it. If streamed, it's difficult for me to say if that's a bug with the app, or a problem related to slow internet connection, or an issue with the podcaster's server.

Screenshot 2: could you create a Github issue for this image loading issue? I've definitely seen it too. When an image doesn't 100% finish downloading, it still gets cached as the incomplete downloaded image.

**Comment by DocDoo** [comment]
> Screenshot 1: was this a downloaded episode? Or a streamed episode? If downloaded, then unfortunately I'm pretty stumped what is going wrong, but I'm hoping fixing #1611 will resolve it. If streamed, it's difficult for me to say if that's a bug with the app, or a problem related to slow internet connection, or an issue with the podcaster's server.

This was with a downloaded episode (I generally configure AutoDownload for my favorite podcasts). I see that, per #1611, version v4.12.3 is assumed to fix this and I have just updated to that version, so I will keep an eye out for a recurrence of this issue.
 
> Screenshot 2: could you create a Github issue for this image loading issue? I've definitely seen it too. When an image doesn't 100% finish downloading, it still gets cached as the incomplete downloaded image.

Will do 👍

**Comment by mitchdowney** [comment]
@DocDoo this is a long shot...but if the issue is still happening for you, can you try turning battery settings to "Unrestricted" for the app sometime, and retest? It seems like Android can do funky things for media player apps due to battery optimization settings. It doesn't make sense to me that would be related, but [this comment](https://github.com/doublesymmetry/react-native-track-player/issues/818#issuecomment-569304463) made me think it might be possible.

**Comment by mitchdowney** [comment]
@DocDoo afaik the episode download resume bug has been fixed. I'm going to close this for now.

**Comment by DocDoo** [comment]
> @DocDoo afaik the episode download resume bug has been fixed. I'm going to close this for now.

Excellent. I've been keeping an eye on how things turned out on my phone and lately I haven't seen album art nor episode audio being partially downloaded. 👍
