### ISSUE TITLE
Add "oldest" sort option to Downloaded filter on Episodes page

### ISSUE THREAD

**Issue by benjaminfvaughn** [podverse/podverse-rn#1563]
**Is your feature request related to a problem? Please describe.**
When I go to the Episodes list, I usually want to listen to the oldest of my downloaded episodes. Currently, when I'm using the Downloaded filter, I have to scroll to the bottom of the list to get to the episode I want to listen to.

**Describe the solution you'd like**
I'd like to have an additional sort option on the Downloaded filter beneath the existing "recent" option that inverts the sort order of the Episodes list:
![podverse_oldest_sort_location](https://user-images.githubusercontent.com/12205846/210030187-82c7f172-28dc-4d92-a11b-c7963e82be50.jpg)
Sorting by "oldest" would have the same sort order as recent, just inverted so that the oldest downloaded episode would be at the top of the Episodes list

**Describe alternatives you've considered**
Possibly, making the scroll position on the Episodes list sticky so that it remembers your scroll position between sessions would help alleviate my problem. (I notice that it remembers your position within a session.)

Thanks for making *the* GPL podcast client for iOS!

**Comment by mitchdowney** [comment]
@benjaminfvaughn thanks for the feature request! I was right about to publish a new Beta, so I decided to throw this filter in there.

![simulator_screenshot_782BA010-D8DC-468C-B889-6D6D153CA9FE](https://user-images.githubusercontent.com/2262919/210039451-92834269-8931-4ec6-8492-c5039e1a3f91.png)

![simulator_screenshot_1C97BC7E-164B-4E09-979A-B0470A6B2BC9](https://user-images.githubusercontent.com/2262919/210039443-b79febc8-efb9-4e6f-bf19-11efd52f3b08.png)

![simulator_screenshot_A21E3B78-0EF4-40A4-A192-C1E53819A360](https://user-images.githubusercontent.com/2262919/210039425-561603e2-7b2e-4c31-a8bd-1c018f2efd8e.png)

I didn't add the sort by oldest filter for non-Downloaded queries, as we don't have the indexes needed on the Episodes table for those queries. The downloaded data is easy for us to sort from device storage though.

> Thanks for making the GPL podcast client for iOS!

You're too kind 😄

**Comment by mitchdowney** [comment]
This should be in v4.10.3

**Comment by benjaminfvaughn** [comment]
Just downloaded v4.10.3 in Test Flight, tested the oldest sort option, and it works like I expected! Thanks again!
