### ISSUE TITLE
Live push notification shows previous album art

### ISSUE THREAD

**Issue by illumiN8i** [podverse/podverse-rn#1600]
**Describe the bug**
You're probably already aware of this issue, but I thought it might be helpful to have an issue open about it. When the 100% Retro live stream changes DJ, a new live push notification is sent out. The text in the new push notification is correct, but the old album art is sometimes still displayed. This means that when a new DJ starts playing, the photo of the previous DJ is sometimes still shown in the notification. This is likely part of a class of bugs related to changes to metadata mid live stream.

**To Reproduce**
1. Enable the notification bell on the 100% Retro Podcast.
2. Wait for a DJ change on the live stream. Schedule is online https://100percentretro.com/
3. Observe the image shown in the push notification does not match the image on the schedule https://100percentretro.com/schedule-saturday/
4. This issue is inconsistent, and it doesn't fail every time. Sometimes it works correctly.

**Expected behavior**
The album art image shown in the push notification should be updated consistently every time.

**Screenshots**
![image](https://user-images.githubusercontent.com/44124235/211181385-cd7ec6c4-1b62-43a8-8146-e9ff132d4f6a.png)
![image](https://user-images.githubusercontent.com/44124235/211181401-21d7b72c-12f3-414a-b501-680134ae7efc.png)

**Smartphone:**
 - Device: Google Pixel 5
 - OS: Android 13
 - App Version 4.10.5 Build 5160

**Additional context**
I'm not completely sure this is a podverse bug. It could be that the live stream isn't actually sending the right information.

**Comment by mitchdowney** [comment]
@illumiN8i I apologize because you made this excellent detailed bug report...and I just tried to fix this about an hour ago. https://podcastindex.social/@mitch/109651438335609480

There were a couple logic errors in our server-side parser that I think explain this issue. Hopefully should be fixed now.

**Comment by illumiN8i** [comment]
No problem. Glad to hear it's fixed! A recent push notification I received was correct, so it seems to be working.
