### ISSUE TITLE
Podverse app is not displaying Castopod activitypub comments

### ISSUE THREAD

**Issue by trevorbell** [podverse/podverse-rn#1614]
**Describe the bug**
Podverse app is not displaying Castopod activitypub comments.

The podcast is https://www.ifvg.info/@ifvg/episodes/morality-what-is-the-right-thing-to-do

The RSS feed includes the following socialInteract tag: <podcast:socialInteract uri="https://www.ifvg.info/@ifvg/posts/c8393034-a2cd-47a3-88e5-da81ed8946cf" priority="1" platform="castopod" protocol="activitypub" accountId="@ifvg@www.ifvg.info" pubDate="2023-01-13T06:00:11+0000"/>

which points to a Castopod instance which has comments: https://www.ifvg.info/@ifvg/posts/c8393034-a2cd-47a3-88e5-da81ed8946cf

![image](https://user-images.githubusercontent.com/28645399/212779465-46141705-c465-480d-9458-f9a005b5ab3c.png)

But the Podverse app does not show any comments. I am able to see comments for other podcasts but I suspect they are for podcasts not using Castopod.

**Smartphone (please complete the following information):**
 - Device: iPhone 11
 - OS: ios 16.2
 - App Version 4.10.6

**Additional context**

Please feel free to [join our Discord](https://discord.gg/6HkyNKR) and chat with us in the #dev channel if you'd like to work on this.

**Comment by mitchdowney** [comment]
@trevorbell is this still an issue for you? I am wondering if the problem is related to some Mastodon instances requiring a public/private key pair for read responses. @johnspurlock was just telling me [we need to update](https://podcastindex.social/@js/109690013215914779) our Mastodon cross-app comments service. I wonder if that is related to your issue?

If the issue is still ongoing for you we can re-open this and integrate the work into the library update we have planned.

**Comment by trevorbell** [comment]
Hi Mitch 

I really appreciate you reaching out on this. 

I’m having success getting my Mastodon instance comments to appear in Podverse so no problem with that. John Spurlock’s validator confirmed my instance does not have any strange blocks.

My problem is with Castopod.

I can’t get the following tag recognised in Podverse to enable comments to appear. The tag is created by Castopod.

<podcast:socialInteract ***@***.***/posts/c8393034-a2cd-47a3-88e5-da81ed8946cf priority="1" platform="castopod" protocol="activitypub" ***@***.***@www.ifvg.info" pubDate="2023-01-13T06:00:11+0000"/>

I created a simpler tag using sovereign feeds and was able to connect to the Castopod instance. But I’ve been mucking around with so many configurations I can’t remember what I did!

Is it possible that Podverse doesn’t like the complicated Castopod tag? Has anyone managed to successfully connect Podverse to Castopod instances?

I did reach out to Castopod but they gave a disinterested response. Basically the dev said she’s never tried Podverse which I thought was a bit strange given their big thing is activitypub and Podverse is the only app that supports it.

If you can solve the Castopod connection mystery I’d be delighted.

Cheers

Trevor

**Comment by mitchdowney** [comment]
@trevorbell hmm I'm sorry, this is difficult for me to debug without a transcript tag in an RSS feed I can test with. It might be a simple logic error that needs to be updated in our API. If you ever have another example of a Castopod feed failing I'd really appreciate it.

**Comment by trevorbell** [comment]
Ok

This feed ***@***.***/feed.xml shows the problem. The first episode “Morality-what is the right thing to do” has a transcript tag. Is that what you need? Podverse shows the transcript but not the comments which are in a castopod instance.

 

Thanks 

 

Trevor

**Comment by mitchdowney** [comment]
Sorry @trevorbell it looks like Github is redacting the URLs in your reply. I assume they do that by default to prevent accidentally sharing personally identifying information in emails. I've included a screenshot so you can see what I'm seeing.

Could you either reply using the Github website, or forward the same message to contact@podverse.fm?

<img width="1030" alt="image" src="https://user-images.githubusercontent.com/2262919/213612522-8cde93ed-453f-456e-8f24-d4b769a4364b.png">
