### ISSUE TITLE
Build arch-specific APKs on F-Droid

### ISSUE THREAD

**Issue by momobobe** [podverse/podverse-rn#1696]
**Is your feature request related to a problem? Please describe.**
The APKs of F-Droid build are getting too big now (over 130 MB recently), which waste much network traffic and storage

**Describe the solution you'd like**
Setup builds for each architecture instead of all-in-one, i.e. each release builds 4 APKs which contain libs for only one arch of armeabi-v7a, arm64-v8a, x86, x86_64

**Describe alternatives you've considered**
Not sure, maybe try removing some unused libs or other components, if any

**Additional context**
You can check other RN apps like [Notesnook](https://github.com/streetwriters/notesnook/releases), [Element](https://github.com/vector-im/element-android/releases), or other apps on F-Droid like [VLC](https://f-droid.org/packages/org.videolan.vlc/), to see how it's done

**Comment by mitchdowney** [comment]
@momobobe thanks for the feature request. It's a really important one. Sadly I know very little about Android architecture, and I spent a day trying to get separate APK builds working, but couldn't figure it out. It also seems like there may be additional work involved for tagging release builds and distributing them to F-Droid.

We'd love to distribute arch-specific APKs, but the work needed for it seems way over my head unfortunately. If there are any members of the F-Droid community who could help drive this APK work forward we would really appreciate it.

**Comment by licaon-kter** [comment]
@momobobe we can take a look...

**Comment by mitchdowney** [comment]
@licaon-kter if anyone has questions and would like a faster response, they can reach us in our [Matrix space](https://matrix.to/#/#podverse-space:matrix.org). Unfortunately I don't know where to begin with this different architecture distribution process, but I will help however I can.

**Comment by licaon-kter** [comment]
I don't do Matrix but will try the known workflow first, from other RN app, and keep you posted.

**Comment by licaon-kter** [comment]
Done https://gitlab.com/fdroid/fdroiddata/-/commit/4420952817193d87ffc64854f8d1680a13a1700c

**Comment by licaon-kter** [comment]
Enabling this: https://github.com/podverse/podverse-fdroid/blob/develop/android/app/build.gradle#L94 or here (as the `sed` hacks it) https://github.com/podverse/podverse-fdroid/blob/develop/android/app/build.gradle#L145 takes care of split ABI

We limit the build APKs as we want: https://github.com/podverse/podverse-fdroid/blob/develop/android/app/build.gradle#L147

versionCode per arch is created here: https://github.com/podverse/podverse-fdroid/blob/develop/android/app/build.gradle#L156-L167

So, be aware that from now on F-Droid's versionCode is... different

**Comment by mitchdowney** [comment]
Wonderful :) thanks again.

**Comment by mitchdowney** [comment]
@licaon-kter I just downloaded Podverse 4.12.7 from F-Droid, and it automatically downloaded the corresponding arch APK 🥳 this reduces the APK file size from ~135 MB to ~45 MB.

45 MB is still quite big for an F-Droid app, and it'd be nice to reduce that further...but a lot of that is unavoidable React Native bloat I believe.

In any case, thank you so much, this is a HUGE improvement for F-Droid.

**Comment by licaon-kter** [comment]
> 45 MB is still quite big for an F-Droid app

U funny, we have 200Mb ones too :)

**Comment by licaon-kter** [comment]
Yes, just tag as usual...
