### ISSUE TITLE
Chapter art not updating on lock screen

### ISSUE THREAD

**Issue by mitchdowney** [podverse/podverse-rn#1705]

**Comment by mitchdowney** [comment]
This appears to be a known issue related to:

https://github.com/doublesymmetry/react-native-track-player/issues/1719

https://github.com/doublesymmetry/KotlinAudio/pull/59

According to @puckey's last comment it should be fixed in nightly + 2.0.0-rc3...but I am still running into the issue of artwork on Android lock screen not updating.

**Comment by KyleFDowney** [comment]
Performs as expected on Podverse 4.13.2, Android 11 (moto g power 2021)

Podcast thumbnail art changes when the phone is on the lock screen, both when the app is actively selected and when it is running in the background.

**Comment by mitchdowney** [comment]
It appears this was fixed in a recent update to react-native-track-player, BUT someone has reported the issue [may have resurfaced](https://github.com/doublesymmetry/react-native-track-player/issues/1719#issuecomment-1660987800) in `4.0.0-rc.6`.

Since there is no issue in Podverse currently, I will close this, but we need to be on the look out in case it resurfaces after we upgrade RNTP again...
