### ISSUE TITLE
Transcript not auto scrolling 

### ISSUE THREAD

**Issue by genebean** [podverse/podverse-rn#1711]
**Describe the bug**
When I listened to https://podverse.fm/episode/h2si6xqrr the transcript didn’t auto scroll, and as far as I can tell, it should have. 

**To Reproduce**
Not sure this will reproduce it, but here’s why I do:
1. Created transcript in Otter
2. Export as srt with proper line and character limit 
3. Upload srt to Buzzsprout 
4. Buzzsprout processes and puts the srt in my rss along with a couple of other versions. 

**Expected behavior**
I expected the transcript to auto scroll

**Smartphone (please complete the following information):**
 - Device: iPhone 12
 - OS: iOS 16.3.1
 - App Version 4.12.2 build 2087, but I think it’s updated since this happened

**Comment by mitchdowney** [comment]
@genebean when you get a chance, can you re-test this, and see if the app still has transcript auto-scrolling issues?

**Comment by genebean** [comment]
Seems to be working great now!

**Comment by mitchdowney** [comment]
@genebean thanks for confirming! 😄

closing this issue.
