### ISSUE TITLE
Podverse does not pause when switching to another audio app 

### ISSUE THREAD

**Issue by jeff-chandler** [podverse/podverse-rn#1720]
If I am playing music, or podcasts in another app (gasp), when I play an episode or clip in Podverse, the audio from the other app (YouTube Music or Pocket Casts) does not automatically pause.  Instead, I need to explicitly pause the other app.  If I switch between YouTube Music and Pocket Casts, or a video app like YouTube or Disney+, the audio automatically pauses on the first app. 

Is Podverse using a different audio channel that allows them to both play at the same time? 

**Expected behavior**
Podverse should pause if playing another app with music or video, or Podverse should pause the other running app if you are switching from a music app to Podverse. 

**Smartphone (please complete the following information):**
 - Device: Google Pixel 6a
 - OS: Android 13
 - App Version:  Beta 4.12.5

**Comment by mitchdowney** [comment]
@jeff-chandler wow...I was completely unaware of this! It seems like there must be a setting or something we are missing. I am asking the react-native-track-player community if they have ideas for how to fix this. That is the audio library we use in Podverse mobile.

**Comment by mitchdowney** [comment]
I asked their Discord channel, and the person who tried to help me could not reproduce the issue. I was able to reproduce the issue with YouTube however.

It would seem there is some kind of setting we are missing, but I'm stumped at the moment. I'll see if the F-Droid chat room has any ideas...

**Comment by mitchdowney** [comment]
@jeff-chandler ok now this is *really* weird. I can't reproduce the issue when I use the F-Droid version of the app. I can reproduce it using the Google Play version however. There shouldn't be a meaningful difference between the players. I wonder if there is some kind of Google Play setting controlling this...

**Comment by jeff-chandler** [comment]
that is strange.  Does it matter that I am in the "Beta" group in the Play Store?

**Comment by mitchdowney** [comment]
@jeff-chandler good point as I am also in the Beta group. I don't think it should affect it...if it _does_ then maybe that points to a permissions issue...but someone in the react-native-track-player Discord group pointed me to this link about handling audio focus on Android, which seems promising: https://developer.android.com/guide/topics/media-apps/audio-focus

**Comment by mitchdowney** [comment]
@jeff-chandler actually, I might have found something. If you're interested in the technical details check out https://github.com/doublesymmetry/KotlinAudio/issues/65

**Comment by mitchdowney** [comment]
I might have a found a setting to handle this: https://github.com/doublesymmetry/KotlinAudio/issues/65#issuecomment-1510220418

**Comment by mitchdowney** [comment]
Will include an attempted fix in v4.12.8.

https://github.com/podverse/podverse-rn/commit/9bfe5bf7218e33ae02ec87afeb838dc23cdd8ed4

https://github.com/podverse/podverse-rn/commit/5c38b190d639187e8faa2744e452ef6744c5e6ac

**Comment by jeff-chandler** [comment]
> Will include an attempted fix in v4.12.8.
> 
> [9bfe5bf](https://github.com/podverse/podverse-rn/commit/9bfe5bf7218e33ae02ec87afeb838dc23cdd8ed4)
> 
> [5c38b19](https://github.com/podverse/podverse-rn/commit/5c38b190d639187e8faa2744e452ef6744c5e6ac)

I have validated that the fix is working in v4.12.8

**Comment by mitchdowney** [comment]
@jeff-chandler great! Thanks for verifying 😄

If you run into any major bugs with v4.12.8 and can let me know I'd appreciate it. There are some settings changes to the Player that could have unintended side effects.
