### ISSUE TITLE
can we keep the search bar accessible [either at all times or when scrolling up a bit]

### ISSUE THREAD

**Issue by gruianovac** [podverse/podverse-rn#1757]
currently when I search for something, to access the search bar I have to go back top. and there is no easy way to do that or to access it.

**Comment by mitchdowney** [comment]
@gruianovac sure, I can try to keep the search bars at the top of the list views.

**Comment by mitchdowney** [comment]
@gruianovac this should be in v4.12.9 https://github.com/podverse/podverse-rn/pull/1778
