### ISSUE TITLE
Give same options for private RSS fees as public

### ISSUE THREAD

**Issue by bxlogan** [podverse/podverse-rn#1787]
**Is your feature request related to a problem? Please describe.**
I cannot queue or mark unplayed private rss podcasts

**Describe the solution you'd like**
Same options as for public

**Describe alternatives you've considered**

**Additional context**

Please feel free to [join our Discord](https://discord.gg/6HkyNKR) and chat with us in the #dev channel if you'd like to work on this.

**Comment by mitchdowney** [comment]
Hi @bxlogan, thanks for the feature requests. I just checked and there are actually 2 Github issues already created for these features.

https://github.com/podverse/podverse-rn/issues/929

https://github.com/podverse/podverse-rn/issues/1240

You could subscribe to those issues for updates. I will close this issue you created and mark it as a duplicate. Please lmk if there's anything more we can do.
