### ISSUE TITLE
Being able to add a local folder

### ISSUE THREAD

**Issue by drenina** [podverse/podverse-rn#1792]
Please add the ability to add a local folder to the podcasts. I have other mp3 files that I also want to listen to through Podverse, most podcatchers let you choose a local storage and scan this folder for new files.

**Comment by mitchdowney** [comment]
@drenina this is a duplicate of an existing ticket. I updated the existing ticket with more info, and will close this one as a duplicate. https://github.com/podverse/podverse-rn/issues/1418
