### ISSUE TITLE
Ability to mark all episodes as played

### ISSUE THREAD

**Issue by drenina** [podverse/podverse-rn#1793]
I am switching over from another podcatcher and would like to mark all epsidoes from podcasts as played - currently I can only select each episode seperately and mark as played...which is a pain if you have over 15 k episodes :/ 

Please add the ability to mark all chosen episodes as played at once.

**Comment by mitchdowney** [comment]
@drenina this is a duplicate of an existing issue. https://github.com/podverse/podverse-rn/issues/885
