### ISSUE TITLE
Ability to Select Notification Interrupt Behavior (and a possible bug report?)

### ISSUE THREAD

**Issue by eroc1990** [podverse/podverse-rn#1798]
**Is your feature request related to a problem? Please describe.**
There's currently no way to define how the player handles notification interruptions (either ducking or pausing the audio feed while the notification audio plays)

**Describe the solution you'd like**
I would like to be able to tell Podverse whether I want to duck the audio playback during notifications or to completely stop playback until the notification sound has completed playback.

**Describe alternatives you've considered**
Checked if there was a device-level way to define this, but it doesn't seem like there is.

**Additional context**
As a side note, I've noticed in the last few releases of Podverse (latest being F-Droid 4.12.10) that the app has been pausing playback during audio notifications whereas before it ducked playback during audio notifications. Not sure if it was an intentional change or not, but it happened.

**Comment by mitchdowney** [comment]
@eroc1990 great idea!

> Not sure if it was an intentional change

This was an intentional change, to make the Android UX have parity with the iOS version...but I don't think it should be difficult to add a setting in More > Settings > Player that allows you to change the "remote duck" behavior.

Here is the code change I believe led to the new behavior: https://github.com/podverse/podverse-rn/commit/5c38b190d639187e8faa2744e452ef6744c5e6ac

What might be a bit complicated though, is tearing down the player, and recreating it with the new setting. I don't think we've done that before, so hopefully teardown / recreate doesn't cause problems.

**Comment by eroc1990** [comment]
Got it. Personally, not a fan of not having an option if this is going to be the default (and don't feel like re-setting up my auto-queues so I'm sticking with current ver haha). But I appreciate the work you and everyone else that contributes to the codebase does.

I wonder if it could be something like:

More > Settings > Player
Setting: Audio Notification Behavior
- Decrease player volume during notifications
- Pause playback during notifications

Would that make enough sense? I'm struggling to find concise wording for each option, so that's the best I can think of right now.  I wouldn't want to make the text wrap too much in the selector. I like how it looks with Other > Main View where the selectable options are short and digestable at a glance.

If it requires explaining the difference between the two options, it might be worth breaking it out into its own submenu within Player, but that might also make navigation too cumbersome just to reach that option.

**Comment by mitchdowney** [comment]
> More > Settings > Player
> Setting: Audio Notification Behavior

> Decrease player volume during notifications
> Pause playback during notifications

That helps a lot, thank you! 🙏

I think it should be relatively easy to add, so I'll add it to my queue.

**Comment by eroc1990** [comment]
Glad to help! It helps makes my favorite podcast player better, so it's a win-win.

**Comment by mitchdowney** [comment]
@eroc1990 I'm just going to revert the Android interruption behavior in the next release so it works like it did before. If people request different interruption handling I may make it a setting, but I'll wait until someone complains.

https://github.com/podverse/podverse-rn/commit/15848945832968138177bcbf8de04ebd9263d1b8

**Comment by ndavis6** [comment]
I would love to have this feature. I find it particularly important if I am using navigation. I would prefer the podcast pause while I get navigation instructions.

Anything I can do to help make this a setting?
