### ISSUE TITLE
Google Play ANR: com.eko.RNBackgroundDownloaderModule.onProgress

### ISSUE THREAD

**Issue by mitchdowney** [podverse/podverse-rn#1804]
This error accounts for 67% of our ANRs on Android!!!

>   at java.lang.Object.wait (Native method)
>   at java.lang.Object.wait (Object.java:442)
>   at java.lang.Thread.join (Thread.java:1426)
>   at java.lang.Thread.join (Thread.java:1507)
>   at com.eko.RNBackgroundDownloaderModule.onProgress (RNBackgroundDownloaderModule.java:394)
>   at com.tonyodev.fetch2.fetch.ListenerCoordinator$mainListener$1$onProgress$$inlined$synchronized$lambda$2.run (ListenerCoordinator.kt:430)
>   at android.os.Handler.handleCallback (Handler.java:938)
>   at android.os.Handler.dispatchMessage (Handler.java:99)
>   at android.os.Looper.loopOnce (Looper.java:226)
>   at android.os.Looper.loop (Looper.java:313)
>   at android.app.ActivityThread.main (ActivityThread.java:8663)
>   at java.lang.reflect.Method.invoke (Native method)
>   at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:567)
>   at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1135)

**Comment by mitchdowney** [comment]
Apparently upgrading to kesha-antonov/react-native-background-downloader was causing a massive amount of ANRs on Android. I'm reverting to react-native-background-downloader as a fix.

**Comment by uzegonemad** [comment]
@mitchdowney Off-topic, sorry, but any chance you were able to identify why the fork was causing so many ANRs? What percentage of your ANRs is caused by the original unforked library by comparison? I was planning on updating my app to use that forked library so curious about your insights.

**Comment by mitchdowney** [comment]
@uzegonemad sorry I didn't try investigating the root of the problem, and I didn't see a Github issue describing the problem, and don't have time to really dig into it...but I can say that after reverting to the unforked library, almost all of our ANRs are gone.

My totally wild guess would be that there was some change in the forked library that ended up with the download process getting handled on the main thread, which would cause the UI to lock up, and the app to run out of resources and ANR in the worst cases.

**Comment by mitchdowney** [comment]
I'm going to close this issue since reverting to the unforked version of the library resolved the ANRs.

**Comment by mitchdowney** [comment]
@uzegonemad I created an issue in the forked version, to see if its maintainer has ideas.

https://github.com/kesha-antonov/react-native-background-downloader/issues/29

Yesterday the upstream version of RNBD stopping building for us, due to jcenter going down...I thought jcenter was going away for good, but now today it appears jcenter is serving artifacts again.

https://status.gradle.com/incidents/7x4wqd7zv715
