### ISSUE TITLE
premium expiration seems like punishment

### ISSUE THREAD

**Issue by gruianovac** [podverse/podverse-rn#1814]
![image](https://github.com/podverse/podverse-rn/assets/27729570/7721b9c5-af4e-47a5-b497-e8ded854daf4) 

not sure if this is a feature or not.. seems weird but, I got the premium as you have offered for testing. now its expired and apparently i cannot subscribe to a new podcast? I dont understand. 
this happened when i hit subscribe.  

Also , getting the renewal subscription banner is annoying., I didnt have it before. is this part of the "
motivation" to get one and is now generic for everyone? hope its a bug,

**Comment by mitchdowney** [comment]
hi @gruianovac the reason why the app fails in various ways after a Premium membership expires is 1) when you're logged in, the app syncs your data to our servers, but 2) when Premium expires, those "sync with server" interactions will fail, and 3) we haven't had the time/energy/resources to make the app handle Premium expiration more gracefully for listeners.

That said, Podverse is a value-for-value company. We will extend the Premium subscription at no cost for anyone who asks us (and they can optionally support us by [other means](https://podverse.fm/contribute)). If you'd like us to extend your membership, can you email contact@podverse.fm, and include the email address of the account you would like renewed?

**Comment by mitchdowney** [comment]
@gruianovac I'm closing this issue. Please let us know if you have any questions or feature requests.
