### ISSUE TITLE
Startup sometimes cycles through podcasts very quickly, doesn't load podcast page and ends up crashing

### ISSUE THREAD

**Issue by mariaa144** [podverse/podverse-rn#1815]
**Describe the bug**
Lately when I have started Podverse, I notice the podcast page doesn't load right away and instead the bottom bar which shows the current podcast flickers through a bunch of podcasts. I try to wait until the flickering is done, which sometimes takes minutes but usually my app will crash before it has completed.

**To Reproduce**
1. Open app with many podcasts already loaded
2. Sometimes on load the current podcast bar will flicker through a bunch of shows quickly
3. At the same time the podcast page will not load.
4. The last thing which will happen is the app will crash or the app will finally stop flickering the shows and the podcast page will load

**Expected behavior**
The Podverse app should load promptly without flickering many shows. Also, the app should never crash.

**Smartphone (please complete the following information):**
 - Device: Pixel 6a
 - OS: GraphineOS
 - App 4.12.12 on the fdroid version
 
 **More context**
I'm not really sure what Podverse is trying to do. I do have Podverse loaded on GraphineOS with Podverse also installed on another profile on the same device.

I'm pretty sure I am always online when my Podverse app does this.

**Comment by mitchdowney** [comment]
Sorry, that is a very nasty crash :(

I haven't run into this one yet, and it will be difficult to fix unless I can reproduce it consistently.

Does the crash happen every time? Or once and a while? If only sometimes, could you estimate about what % of the time it happens for you?

There is one [pretty major/common bug](https://github.com/podverse/podverse-rn/issues/1702) that we are aware of in the Android version right now, and the fix appears to be dependent on [changes needed to react-native-track-player](https://github.com/doublesymmetry/react-native-track-player/issues/1986). The RNTP community seems perplexed about how to proceed though, and none have a clear idea of what we need to do to fix it.

If the error linked above were to happen for you, then the player would not be able to start properly, and then *maybe* that could result in the behavior you're seeing where the player and queue freak out, and trying to play each track one-by-one, failing each time. I don't know...just a thought.

If you ever have more info on how to reproduce the bug, please let us know. Thanks for the report!

**Comment by mariaa144** [comment]
I'm not sure if that issue linked is affecting me. The issue I'm reporting happens to me about once a day on both profiles where I have Podverse installed. The app seems to be going through the queue possibly or loading new shows from feeds. I'm not sure which.

**Comment by mitchdowney** [comment]
@mariaa144 there was a bug that resulted in a similar behavior [fixed in v4.12.13](https://github.com/podverse/podverse-rn/issues/1799), which is available now on the App Store and Google Play. I submitted the new version to F-Droid, but it usually takes 5-8 days before it appears. When you have a chance, can you try 4.12.13, and see if the issue still occurs for you?

I'm going to mark this as "ready to deploy" but there's a good chance this isn't fixed yet.

**Comment by mariaa144** [comment]
I installed the v4.12.13 and I haven't see the issue again. I also cleared my queue which was getting very large. I think the issue might have had something to do with the queue.

**Comment by mitchdowney** [comment]
That's great to hear! Thanks for following up @mariaa144
