### ISSUE TITLE
Support TimeValueSplit

### ISSUE THREAD

**Issue by captain-egghead** [podverse/podverse-rn#1823]
**Describe the solution you'd like**

Want my sat-streams/boosts to go to the value-block of the song that is being played...

https://github.com/Podcastindex-org/podcast-namespace/blob/main/docs/1.0.md#value-time-split
(Already being used in the Podcasting-2.0 podcast. Podfriend & CurioCaster already support this)

**Comment by mitchdowney** [comment]
Thanks for the feature request. There's already one open #1810, so I'll move your request over there.

**Comment by captain-egghead** [comment]
Thanks and sorry...
Just wanted an issue ID so I can boost it.
(next time will search better ... )
Boosting another 1810 now

**Comment by mitchdowney** [comment]
@captain-egghead it's ok! Thanks for the feature request and the boost :)
