### ISSUE TITLE
Keep a changelog

### ISSUE THREAD

**Issue by frmayall1978** [podverse/podverse-rn#1871]
I received an update for podverse-fdroid, but there is no way for me to see what changed. Tried looking for some release notes, but couldn't find any, not even in "Releases" section. If you really don't have a changelog, then it would be good of you to have one. It's nice to know what changed from one version to another, especially when an update is, say, 80MB. Not this case, but understand my thought.

I checked for issues regarding changelog and relesse notes, but couldn't find any. If I'm mistaken and you DO have a changelog, then point me to it and close this issue.

**Comment by mitchdowney** [comment]
hi @frmayall1978 hmmm I am also confused. We do release changlogs to Apple, Google, and F-Droid with each release. I *thought* the changlogs were visible in the F-Droid Store, but for some reason I'm not seeing them. I wonder if something changed recently. I'm asking the F-Droid Matrix room for help with the issue.

Release documentation is something we could probably use help with. If someone wanted to document and/or own a more proper changelog process we'd appreciate it.

https://github.com/podverse/podverse-fdroid/tree/develop/fastlane/metadata/android/en-US/changelogs

**Comment by mitchdowney** [comment]
more info in screenshot:

![image](https://github.com/podverse/podverse-rn/assets/2262919/fab7b094-fe28-4541-925d-1cbe710fe36c)

**Comment by frmayall1978** [comment]
Thank you for a good reply. Glad to have brought this up. Will be keeping an eye on this with you 😸

**Comment by mitchdowney** [comment]
@frmayall1978 nah I'll keep it open and assigned to me. @kreonjr and I are going to work on a script/s to help us with our F-Droid release process, so that the duplicate changelog files are automatically created with every future release.

**Comment by frmayall1978** [comment]
Awesome! May your scripts run without errors.

**Comment by mitchdowney** [comment]
@kreonjr thanks for the `prepare_release.sh`! I just used it for v4.13.3 release and it worked great.

There is one thing missing though...we need to programmatically generate copies of the changelogs in the fastlane directory so that they follow this pattern:

```
87.txt
87001.txt
87002.txt
87003.txt
87004.txt
```

Maybe that should be a separate script in case I forget to create the file first? Or add a check that warns us the root changelog (`87.txt`) doesn't exist, and to exit?

**Comment by frmayall1978** [comment]
> There is one thing missing though...we need to programmatically generate copies of the changelogs in the fastlane directory so that they follow this pattern:
> 
> ```
> 87.txt
> 87001.txt
> 87002.txt
> 87003.txt
> 87004.txt
> ```
> 
> Maybe that should be a separate script in case I forget to create the file first? Or add a check that warns us the root changelog (`87.txt`) doesn't exist, and to exit?

You mean something like:

```
...
DIR='fastlane/metadata/android/en-US/changelogs'

if [ "$2" == "--update" -o "$2" == "-u" ] && [ "$3" ]; then
	echo -e "\nHandling changelogs:\n"
	
	num=$(find $DIR/ -type f -iname "$3*.txt" | wc -l)
	
	if [ "$num" -eq 0 ]; then
		echo -e "Root changelog file $3.txt does not exist. Skipping...\n"
	fi
	
	if [ "$num" -gt 1 ]; then
		echo -e "There are already copies for $3.txt\n"
	fi
	
	if [ "$num" -eq 1 ]; then
		echo -e "Creating copies of the root changelog file $3.txt...\n"
		cp $DIR/$3".txt" $DIR/$3"001.txt"
		cp $DIR/$3".txt" $DIR/$3"002.txt"
		cp $DIR/$3".txt" $DIR/$3"003.txt"	
		cp $DIR/$3".txt" $DIR/$3"004.txt"
	fi
fi

```

?

Don't know if sequential numbers for that txt file will always be 001-004 or more, depending on version; I assumed the first, but in latter case the code should, obviously, be changed a little. Also not sure if the update number have something to do with source code version  number or is it just a symbolic sequential number. If it **does** work, then append this to the `prepare_release.sh` script and use it like you did before, but with a `--update [update number]` option at the end.

Example: ./prepare_release.sh 12 --update 69

It will look for 69.txt in the changelog dir and, if it's there and it's lonely (i.e. there are no files like 69001.txt, 69-copy.txt, etc), it will create 69001.txt, 69002.txt, 69003.txt and 69004.txt.

**Comment by mitchdowney** [comment]
@frmayall1978 I just tested created a file called `prepare_changelogs.sh` and it worked like a charm! Thanks for your help 😄

@kreonjr work is complete for this issue so I'll close it.
