### ISSUE TITLE
Podcasts fail to play in mobile browsers

### ISSUE THREAD

**Issue by KyleFDowney** [podverse/podverse-rn#1880]
Podcasts fail to play when the play button is tapped in mobile browsers.

Tested and failing to play on:
Android - Chrome
Android - Mozilla

**Comment by mitchdowney** [comment]
I also tested with iOS - Safari and had the same issue. This is a critical error so I'll move it to the top of my priority list.

**Comment by mitchdowney** [comment]
This should be fixed in web 4.13.7 https://github.com/podverse/podverse-web/pull/1166
