### ISSUE TITLE
Transcripts do not show on Episodes > Transcript screen until you press play

### ISSUE THREAD

**Issue by mitchdowney** [podverse/podverse-rn#1889]
Thanks to genebene on the Fediverse for reporting this bug.

**Comment by Marzal** [comment]
Not sure if is the same problem, in my case transcripts do show in the player section but not in Episodes > Transcript even after pressing play.

Tested with Podcasting 2.0 podcast and https://podverse.fm/episode/yuY4qZ4Cc

Podverse F-droid 4.13.4

https://github.com/podverse/podverse-web/issues/1168

**Comment by mitchdowney** [comment]
A fix for this should in v4.13.6. It was a missing style rule 🙈

![image](https://github.com/podverse/podverse-rn/assets/2262919/3588c5d0-b6c7-4ffa-9d0f-9b67ae11ffb9)
