### ISSUE TITLE
Text in number selector does not display (sleep timer, Android only)

### ISSUE THREAD

**Issue by mitchdowney** [podverse/podverse-rn#1921]
> I have a very old phone, it lacks the ability to select dark/light themes, xiaomi redmi note 5A, Android version 7.1.2N2G47H, I found this bug in the podverse app from google play, in the version from the f-droid store, this bug is also present

Maybe there is an easy way to fix this issue? Could it be Android 7 related? Or specific to this listener's device settings? Unfortunately I'm not sure what to do due to my lack of Android knowledge.

![IMG_20230825_215402](https://github.com/podverse/podverse-rn/assets/2262919/ee73ccdc-fef3-405e-bfd7-0ef1b3c471ee)

**Comment by lovegaoshi** [comment]
~A stupid way is to return the android build number in a native module, and adjust font colors accordingly (I assume it's due to a theme problem)~
~But as evil as I am, i would raise the minimumSdk to something higher~
Seems like it's happening to me too, android 13 debug
![Screenshot_20230905_073615_Podverse](https://github.com/podverse/podverse-rn/assets/106490582/8d617066-7458-4bbd-9c3b-8367e682556f)

**Comment by lovegaoshi** [comment]
Seems like a problem with dark theme. Time is always in dark folor
And light theme could use a light background color in some components too, but I'm sure you're already aware
![Screenshot_20230905_073931_Podverse](https://github.com/podverse/podverse-rn/assets/106490582/8c7d49b2-f0f2-4fc6-87e0-5e989fee713a)

**Comment by mitchdowney** [comment]
@lovegaoshi we actually a [bounty for light-theme](https://github.com/podverse/podverse-ops/blob/master/bounties/mobile/react-native/light-mode.md) support, on both mobile and web. We have handling added for light mode already, and making the style changes is _relatively_ easy, but it is tedious work, so we just haven't been keeping up with light mode.

But regarding this specific bug...I just tried on Android Emulator with Android 10, and I _can_ reproduce the bug. 

There are two things I wonder if could be the source of the problem...one is that we are stuck on the picker version 1.16.8...but the latest version is [2.5.0](https://github.com/react-native-picker/picker/tags). The problem is, when I try to upgrade the picker version, the app crashes on launch, and it appears it [may be related](https://github.com/react-native-picker/picker/issues/278) to the fact we are using such an old version of React Native (0.66.5). Upgrading RN seems like a good idea, but it would be a lot of work, and personally I may need help with that...

Another possibility is, do we need to update our AndroidManifest.xml file somehow? I see `AppTheme` [in there](https://github.com/podverse/podverse-rn/blob/develop/android/app/src/main/AndroidManifest.xml#L35).

The [SleepTimerScreen](https://github.com/podverse/podverse-rn/blob/develop/src/screens/SleepTimerScreen.tsx#L58) uses a `TimePicker` component, and that component uses `@react-native-picker/picker`, and we attempt to set the color of the font using the `globalTheme.text` [style](https://github.com/podverse/podverse-rn/blob/develop/src/components/TimePicker.tsx#L78)...but I guess Android needs the color set at a lower level to the Android API?

**Comment by lovegaoshi** [comment]
it could be TimePicker also needs globalTheme.text in its style prop, but in however style format they specifies of course. maybe they now have Appearance.getColorScheme() support but not before

**Comment by mitchdowney** [comment]
@lovegaoshi 😦 oh my goodness...it really was that easy. Thank you so much

![image](https://github.com/podverse/podverse-rn/assets/2262919/9d513a45-0df1-4671-8636-7f5219c7d0b8)

**Comment by mitchdowney** [comment]
This should be in v4.13.9
