### ISSUE TITLE
Make Podverse Mission Statement translatable

### ISSUE THREAD

**Issue by mitchdowney** [podverse/podverse-rn#1926]
There are some instances of text in the web and mobile app that we have purposely not allowed to be translated into other languages. My primary reason for doing with this text is that I want to be extra careful and do extra review, since this text may relate to our mission statements as an organization, or have legal implications.

That said, maybe I am being overly cautious. I'm not sure how to proceed on this at the moment, but I think it would be useful to at least organize examples of the screens / pages that are not translatable at this time for those reasons.

![Screenshot_2023-09-03-14-31-29-579_com podverse](https://github.com/podverse/podverse-web/assets/2262919/2f7a6bdb-5331-49f0-8b9a-f70018c07e6d)

related to: https://github.com/podverse/podverse-web/issues/1185

**Comment by Marzal** [comment]
Hi, just yesterday I updated de Spanish translation of podverse-web and I did have available that string to translate.

Is the lock in the PR bot on GitHub?

https://hosted.weblate.org/translate/podverse/podverse-web/es/?q=Podverse+creates+free+and+open+source+software+to&sort_by=-priority%2Cposition&checksum=

**Comment by mitchdowney** [comment]
@Marzal that "Mission statement" string should be translatable and should surface in the web app. I'm not sure I understand your question? If you are wondering why the changes aren't reflected on the web site yet, I just need to release a new version of the web app. It's a very simple process with our Github Actions, so I will do that right now.

Also, thank you very much for the Spanish translations! You did a *lot* of work there.

**Comment by Marzal** [comment]
@mitchdowney let me reformulate:
In the image, what's the text that is not translatable? I thought it was the part in English, but some of these strings in English are available for translation in the platform. I was asking, just in case I have to mark them with "revisar" to have a special review with them.

The platform makes translation quite easy, the next time my daughter is out with her grandpa I will try to do the Mobile app strings.

**Comment by mitchdowney** [comment]
@Marzal ahh, so, the link you provided is actually for the podverse-web repo, which is for the website, but this ticket is for the mobile app, so I was confused. This text you're seeing in the screenshot could be translatable. It's more of the legal-related text I'm concerned about. I'll assign this ticket to me so I remember to make the text translatable in the mobile app.

**Comment by mitchdowney** [comment]
@Marzal this should be translatable as of 4.15.1
