### ISSUE TITLE
iOS App unable to download episodes when server uses HTTP/2 

### ISSUE THREAD

**Issue by eta-orionis** [podverse/podverse-rn#1948]
The iOS App seems unable to download episodes when the server uses HTTP/2. The feed itself is downloaded and shown without a problem, but trying to download or play an episode results in a warning triangle shown on the play button after a while (see screenshot). 

I have confirmed that by turning off HTTP2 on the server the problem disappears. No other configuration change was necessary. With HTTP/1.1 everything works, with HTTP/2 episodes do not play.

I am pasting the response headers as well, just in case they might play a role. (These were generated by cURL-ing the episode's URL. I don't have a MITM proxy to capture the actual headers from/to Podverse, but I can't imagine they would be different).

``` 
HTTP/2 200
server: nginx
date: Tue, 26 Sep 2023 14:59:39 GMT
content-type: audio/mpeg
content-length: 12345
x-powered-by: PHP/x.x
content-disposition: attachment; filename=9f143ea9-some-long-filename-hash-here.mp3
cache-control: private, must-revalidate
pragma: no-cache
expires: -1
set-cookie: some-cookie=long_string_value; expires=Tue, 26 Sep 2023 16:59:19 GMT; Max-Age=7200; path=/; samesite=lax
set-cookie: some-session=long_string_sessionid; expires=Tue, 26 Sep 2023 16:59:19 GMT; Max-Age=7200; path=/; httponly; samesite=lax
```

**To Reproduce**
The podcast I am playing with is private and on an internal server, so I can't provide a public URL. But as I said, HTTP/2 seems enough to trigger the bug.

**Expected behavior**
The podcast episode should play no matter what HTTP protocol is used.

**Screenshots**
![image](https://github.com/podverse/podverse-rn/assets/3466670/e99bdf90-742e-4dd7-ba6d-4f689aa1d55a)

**Smartphone (please complete the following information):**
 - Device: iPhone 14
 - OS: 16.6.1
 - App Version 4.13.9 build 2317

**Comment by mitchdowney** [comment]
@eta-orionis thanks for creating this. To be honest, I don't know much about HTTP/2. I mostly know JS and Node.js. I just wanted to mention that I sent your issue to @suorcd, and he said these 2 podcast feeds appear to use http2, yet they seem to download and play in Podverse iOS mobile:

https://podverse.fm/podcast/peLVTHMwlg
https://podverse.fm/podcast/3zOFRDffQd

Could there be something else specific to this server leading to the issue?

Given that it is a private feed you can't share with us, I'm not really sure how to proceed with this issue. Ideally I'd want to try to reproduce the bug while running Podverse mobile locally, where I could inspect the logs and see if a useful error message appears. We have a [start-up guide](https://github.com/podverse/podverse-ops/blob/master/docs/how-to-setup-local-environment-with-test-data.md) if that's something you'd be interested in trying to do yourself.

Could the issue be SSL related? Only content with valid SSL will reliably play in Podverse. I think iOS is especially strict about this requirement.

**Comment by eta-orionis** [comment]
Thank you @mitchdowney and @suorcd for taking the time and especially for the links. They didn't work initially, so the problem *had* to be with my installation of the app. After uninstalling/reinstalling, things magically worked. No idea what the problem was (especially since it was a fresh install and I was deleting all downloads and emptying the cache between trials). 

Thanks for the start-up guide too - I'm not familiar with RN so that will definitely be helpful.
