### ISSUE TITLE
Create a F-Droid beta repo

### ISSUE THREAD

**Issue by Marzal** [podverse/podverse-rn#1974]
**Is your feature request related to a problem? Please describe.**
Changing between the F-Droid APK and a beta outside F-Droid implies deleting app data.

**Describe the solution you'd like**
A F-Droid beta repo could solve this and make easy to beta test the app. And will probably always faster than the F-Droid official repo path.

**Describe alternatives you've considered**
There seems to be an option to tag releases so they are not offered for auto-download/install and just show with "unstable versions":
https://forum.f-droid.org/t/beta-versions-in-fdroiddata-metadata/9779
https://gitlab.com/fdroid/fdroidserver/-/issues/161

**Additional context**
Official documentation for F-Droid repos: https://f-droid.org/docs/Setup_an_F-Droid_App_Repo/

**Comment by mitchdowney** [comment]
@Marzal I'm open the idea, but I've already put a lot of effort into intricacies of setting up F-Droid, and tasks related to it often turns into a lot of time for me. If someone wants to lead this effort and can provide docs for what we need to do as maintainers to keep it up to date, I think @kreonjr and I would be ok with it, but I don't think we're going to lead the effort ourselves.

**Comment by mitchdowney** [comment]
@Marzal so we have Azure pipelines that we use to build the F-Droid app (and the beta APK), prior to tagging the master branch, which F-Droid then automatically detects and merges into their repo, which then has its own separate environment, the details of which I am not sure of.

But I think our Azure pipeline page is publicly visible: https://dev.azure.com/podverse/podverse-fdroid/

The repo situation is a bit confusing...we have podverse-rn which is our upstream repo, and then podverse-fdroid which has our "untainted / 100% FOSS" version of the app. Here is a pipeline config in podverse-fdroid: https://github.com/podverse/podverse-fdroid/blob/develop/develop.yml

There is a azure-pipelines-post-build.sh file, but you can ignore it as I don't think we use it. It was intended for uploading the APK to BrowserStack for tests, but we don't use that now.

Our F-Droid build config file can be found here: https://github.com/podverse/podverse-fdroid/blob/develop/fdroid/com.podverse.fdroid.yml

And we use this script we wrote to make it easier to tag qa, beta, and release builds:
https://github.com/podverse/podverse-fdroid/blob/develop/prepare_release.sh

There's also a little script there for generating changelogs for all architecture types (prepare_changelogs.sh).

Also, the branches we use for F-Droid builds are the develop (qa), master-beta (beta), and master (prod) branches, and I think there's a corresponding Azure config in podverse-fdroid for each of those.

Hope that helps 😅 thanks for your interest in this. The "delete and reinstall" requirement for F-Droid beta testing is a major painpoint for testers.

**Comment by Marzal** [comment]
Thanks for the info, a lot to chew, but just with :
https://github.com/podverse/podverse-fdroid/blob/develop/fdroid/com.podverse.fdroid.yml
and 
https://forum.f-droid.org/t/beta-versions-in-fdroiddata-metadata/9779/2

I think that I get how to make available betas to F-Droid, without setting up new servers or repos, It would only need a MR (when there is a new Beta) to https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/com.podverse.fdroid.yml and anyone would be able to manually install them or enable "update to unstable/beta versions" to have beta notifications.

Some projects are doing that, for instance [Aurora Store](https://gitlab.com/fdroid/fdroiddata/-/commit/7fe43bab92ef2f62079b079ff632903bbba3aa78), they add the new build without updating the `CurrentVersion`and 
`CurrentVersionCode` tags


https://f-droid.org/es/packages/com.aurora.store/
![imagen](https://github.com/podverse/podverse-rn/assets/2069735/57ea129f-a41c-4fe6-8726-71ffdb004840)



As soon as I finish my competitive exam I will look this trough and report back.

**Comment by mitchdowney** [comment]
@Marzal ah, if I'm understanding you correctly, I forgot about the official F-Droid Store way of sharing beta the releases. We never went that route because after we submit builds to F-Droid, it usually takes ~7 days before it actually becomes available in the F-Droid Store. Our release cycles are usually too fast for that to be useful for us (when we're really focused, and I am since I temporarily quit my day job). Last year we averaged 1 new release per week, so I think we'd run into a bottleneck if we need to wait a week for F-Droid betas to be available, and then wait a few days for tester feedback.

**Comment by suorcd** [comment]
This is still a work in progress.

https://files.podverse.fm/fdroid/repo/

I have successfully installed an app from this repo on a pixel 5 with f-droid, nothing else has been tested.


If this works more work will be needed to make a real process of it.

And I'm not sure what I'm doing wrong with the icon.png

**Comment by Marzal** [comment]
Great! I installed the repo and it's shows the app. :+1: 
But it doesn't show any new version (4.14.2 ...), is there any place to see what it's the repo offering?
Just to check the `CurrentVersionCode`
What I have installed right now is  4.14.0 (94003) 

> And I'm not sure what I'm doing wrong with the icon.png

Have you checked in `fdroid/config.yml` 
`repo_icon = "GP_Logo_hires.png"`

**Comment by mitchdowney** [comment]
@Marzal I'm actually asking the [F-Droid Matrix channel](https://matrix.to/#/#fdroid:f-droid.org) about how to handle missing metadata right now. Will report back if I get an answer.

**Comment by suorcd** [comment]
We had added that icon.png still was having some issues. After @mitchdowney chatted with them, we got the needed info for the images and summary text; sans the changelog info, still working on that.

As for the other metadata fun that is still a work in progress. I'm still working on what figuring what is needed. I'll probably ask in the room again, the workspace is hard since there are many colliding namespaces.

**Comment by mitchdowney** [comment]
The F-Droid beta repo is up and running thanks to @suorcd's help 🎉 

Here's the beta signup doc: https://github.com/podverse/podverse-rn/blob/develop/docs/how-to-join-podverse-for-fdroid-beta-track.md

If we need to make additional adjustments to the F-Droid repo or its process, let's create a new ticket for it.
