### ISSUE TITLE
Allow time jump forward, time jump backward, skip track, and previous track using bluetooth (headphones) buttons

### ISSUE THREAD

**Issue by mitchdowney** [podverse/podverse-rn#2009]
> It would be great to be able to control the rewind and fast forward using my Samsung galaxy buds touch controls.
> Also, not sure if this is connected, it would be great to control the rewind/fast forward using vehicle controls on android auto. 

I'm actually not sure how or if this is possible, as I have personally only ever used play/pause bluetooth earbud controls with apps. If anyone has input on this I'd really appreciate it.

**Comment by lovegaoshi** [comment]
while i didnt really test this (i dont have a galxy bud either to confirm), any rewind/forward events I found are now registered for podverse in this commit:
https://github.com/lovegaoshi/KotlinAudio/commit/a8990b57ae6cff0d85f9139d20d725ffbe224ed8

Maybe these changes can be also pushed to doublesymmetry's main branch so podverse doesnt have to maintain one, but here we are now:S

**Comment by mitchdowney** [comment]
@lovegaoshi Nice! Do you know if additional changes are needed in Podverse to support it (besides syncing with your fork), or should this work out of the box for bluetooth devices that have rewind/forward? I'm still not sure how I can test this...buying a device that supports it is an option if we know of any that aren't crazy expensive.

**Comment by lovegaoshi** [comment]
It should be plug and play once podverse updates the rntp dependency from
my pr;
If there's a particular headset not working but a tester is willing to do
some logcats, I think we need to look for com.android.bluetooth and
something about media button event sent

**Comment by lovegaoshi** [comment]
had a chance to try out my Sony MDR1000X, it uses KEYCODE_MEDIA_FAST_FORWARD. its already implemented.

```
2023-10-27 18:13:41.068  1677-6050  MediaSessionService     system_server                        I  tempAllowlistTargetPkgIfPossible callingPackage:com.android.bluetooth targetPackage:com.noxplay.noxplayer reason:action=ACTION_DOWN;code=KEYCODE_MEDIA_FAST_FORWARD [WIU] [FGS]
2023-10-27 18:13:41.524  6331-6687  bt_stack                com.android.bluetooth                I  [INFO:device.cc(1411)]  : 045d4b : MessageReceived: OperationId=I, KeyState=KeyState::RELEASED
2023-10-27 18:13:41.524  6331-6687  bt_stack                com.android.bluetooth                I  [INFO:device.cc(1493)]  : 045d4b : MessageReceived: released seek key
```

**Comment by mitchdowney** [comment]
I believe this was deployed in v4.14.2. Thanks again @lovegaoshi!
