### ISSUE TITLE
Streams get paused everytime I re-open the app

### ISSUE THREAD

**Issue by tvnmguy** [podverse/podverse-rn#2016]
Podcast streams get paused everytime (both online streams and downloaded/offline streams) I re-open the app. Which is super annoying for me and pain in the neck.

**Actual behavior**
1. Open Podverse app.
2. Click to play a podcast.
3. Click android navigation back button and close the app.
4. Re-open Podverse app.
5. See the error.

**Expected behavior**

Like AntennaPod and Spotify managing their app.

**Screenrecords**
https://github.com/podverse/podverse-rn/assets/116799295/468b3fc9-a5a8-426b-87a6-c59ae6b7abfc

**Smartphone**
 - Device: Redmi note 8 pro.
 - OS: MIUI 12.5 based on Android 11.
 - App Version: 4.14.2.

**Comment by lovegaoshi** [comment]
This is an rntp issue, I have this too in my app.
I think this could be related to RNTP initializing the service on start up and killing existing service due to serviceOnAppKilled set to whatever we are using. I have no idea how to fix though, I might look into it for RNTP when I have time.

**Comment by lovegaoshi** [comment]
In the mean time your home is closing podverse (the activity) on app exit where it should be to background, causing calling setupPlayer on podverse startup I guess and this this behavior. I guess it might be related to your optimization setting?

**Comment by mitchdowney** [comment]
@lovegaoshi do you know if there is an existing issue for this in RNTP's issue tracker? That we can cross-reference here?

If not np, I just tried looking and didn't see/recognize it. https://github.com/doublesymmetry/react-native-track-player/issues?q=is%3Aissue+is%3Aopen

**Comment by lovegaoshi** [comment]
I didn't check but I don't think it's an active issue at least.

**Comment by mitchdowney** [comment]
@lovegaoshi ok np.

I've seen several major podcast apps on Android request users to turn off battery optimization...we already request so many prompts for first-time users 😭 but maybe this is important enough we should do it too. Maybe we ask people to disable battery optimization the second-time they open the app instead.

@tvnmguy if you ever get a chance, and if you don't have it disabled already, could you try disabling battery optimization for Podverse, and let us know if the issue persists or goes away?

**Comment by lovegaoshi** [comment]
Oh wait - podverse can make it an option to set appkilledplaybackbehavior
to continueplayback to avoid being killed/stop playback. Doesnt it sound
shady though?

**Comment by mitchdowney** [comment]
@lovegaoshi hmm I don't know what the ramifications of that would be. Also, if most Android users don't need it, it _sounds_ like a heavy config decision to make. Is this something we could add a toggle for in the app's Settings screen? Some kind of advanced player debugging setting toggle?

**Comment by lovegaoshi** [comment]
Yeah it has to be a config - it's too shady for me bc with it podverse
would just linger on my phones notif area. But it would be the ultimate
solution to any battery optimization problem I think, only one RNTP.config
away, since the service would never quit foreground willingly.

**Comment by lovegaoshi** [comment]
RNTP can call updateOptions whenever - config stored in asyncstorage would
be okay

**Comment by mitchdowney** [comment]
@lovegaoshi ok cool, thanks so much for the info 🙏 it should be easy to add the setting, so people can try this at least as a fix if they run into the issue. I'll assign this to me.

**Comment by mitchdowney** [comment]
@tvnmguy @lovegaoshi I'm including a new toggle on the More > Settings > Debugging screen. This should force the player to stay active even while in the background. The downside expected is increased battery usage by the app. Unfortunately I'm not sure we'll have a better solution than this toggle.

This should be in v4.14.3.
