### ISSUE TITLE
Alby wallet is getting disconnected before the refresh token expires

### ISSUE THREAD

**Issue by mitchdowney** [podverse/podverse-rn#2023]

**Comment by mitchdowney** [comment]
This should be fixed (finally!) in v4.14.3.

**Comment by clayt0nk** [comment]
v4.14.3 came down from FDroid a couple days ago. Early experience was promising, a couple old episodes of two different podcasts that had downloaded without v4v way back when, recovered their v4v capability sometime after I started playing them. Today I donwloaded NA Ep.1608, and just to be helpful, it downloaded without v4v again. I started playing and left it going for a long time, but nothing changed. I stopped the app (swiped up on Android) but audio kept playing. I tapped the app icon and the GUI spun up again, and audio stopped. Permanently. I could not get any sound out of Podverse, even though Podverse was not frozen and responded to my gestures. Rebooted the phone. Resumed playing the same broken NA episode, audio worked, still no v4v at well over an hour into the episode. I should mention immediately before listening to NA I was listening to another episode of a v4v podcast and streaming sats just fine. Switched to NA episode and it all disappeared, despite verifying somewhere in there that Podcast was still reporting being "connected" to Alby.

**Comment by mitchdowney** [comment]
I think our fix for the "wallet disconnected" issue _might_ still have worked, but the problems the app is giving you is probably a continuation of what is in #1701. I'm going to paste your comment and reply over there to keep our comment history together.
