### ISSUE TITLE
Hide completed setting in episode view

### ISSUE THREAD

**Issue by beglitched** [podverse/podverse-rn#2029]
On Podverse mobile…

When looking at a list of all episodes available from a podcast, I can select “Hide completed” when clicking the sort options. 

When looking in the Episodes tab, that option is not available.

I found the setting in Settings>Other but it seems like it should be consistent and be available in the same place for both- in the sort options section.

**Comment by mitchdowney** [comment]
hi @beglitched thanks for the feature request. We actually already have an issue created for this #1800 but I'll mark that as a duplicate and keep your version open.

**Comment by mitchdowney** [comment]
@beglitched this should be in v4.15.1
