### ISSUE TITLE
Downloaded episodes result in stale podcast image artwork hanging around on the EpisodesScreen

### ISSUE THREAD

**Issue by mitchdowney** [podverse/podverse-rn#2073]
This was reported by @suorcd, and is noticeable with the No Agenda podcast, as they change the podcast artwork every time a new episode is released. I think the data we save locally when an episode is downloaded is overriding the new image artwork somehow.

**Comment by mitchdowney** [comment]
@suorcd I think this issue may be happening because we only load shrunken images (which we host in S3) in list views, and we currently only shrink and host the podcast-level artwork for a podcast (not the episode-level artwork). Does that sound like the bug you reported, or was your bug different?

**Comment by suorcd** [comment]
closing for now. I think there were other things involved with this. the podcaster would change the podcast art and the episode art
