### ISSUE TITLE
Add Apple AirPlay support

### ISSUE THREAD

**Issue by mitchdowney** [podverse/podverse-rn#2103]
It appears that as of today react-native-track-player does not support Apple AirPlay, so this will be blocked until the feature support is available in RNTP:

![image](https://github.com/podverse/podverse-rn/assets/2262919/6da05c6b-de78-40f6-89f8-bd44b2b610dd)

https://rntp.dev/docs/next/basics/platform-support#casting

**Comment by beglitched** [comment]
Came here to submit something about AirPlay not working. 

I can tell Podverse to send to AirPlay, audio stays coming out of iPhone speakers though it looks like AirPlay is selected. Then switch audio back to iPhone in AirPlay menu, pause playback. Then switch back to an AirPlay device and it will play from the AirPlay device. When I switch to another app and Podverse goes to the background, AirPlay settings change back and the audio starts playing from iPhone speakers.

**Comment by beglitched** [comment]
It's working in 4.16.1! Thanks so much for fixing this!!

**Comment by mitchdowney** [comment]
@beglitched glad it's working! 🥳 you're welcome
