### ISSUE TITLE
App is taking up excessive storage (stray downloaded episodes are not being deleted properly?)

### ISSUE THREAD

**Issue by mitchdowney** [podverse/podverse-rn#2126]
Possibly iOS only?

> I don’t understand why the app is taking 14 gigs of data. My settings don’t allow for any downloads automatically and I have setting to delete once done.

When I checked my app installed, I had 11GB. I went to Settings > Downloads and Settings > Other and deleted both, but the app only dropped to 5GB installed.

The only way I was able to remove the excess storage being used was to delete and reinstall the app 😕 after a fresh install, the app only took up 30MB, so it would appear that somehow downloaded episodes are getting stuck in our app storage, and cannot be removed.

At a minimum, we need a way to make the "delete downloaded episodes" button in settings to actually delete _all_ audio/video files, not just the ones that we have references saved to for downloaded episodes.

Ideally we need to figure out how these files are getting lost in app storage in the first place and prevent it from happening.

**Comment by lovegaoshi** [comment]
i had a similar problem, it was due to RN-blob-util had incomplete downloads that lingered in the temp folder; i ended up with a button that does a ls from the temp folder and deleted all files that is not registered with my app.

**Comment by mitchdowney** [comment]
This should be in v4.16.0.
