### ISSUE TITLE
Incorrect splits percentage display

### ISSUE THREAD

**Issue by mitchdowney** [podverse/podverse-rn#2137]
This bug was reported by @joksas. 

> Podverse on mobile is showing splits as if they were percentages:

![image](https://github.com/podverse/podverse-rn/assets/2262919/02773a7b-0c29-4996-8f26-a7114dcb95fb)

> Sat amounts are calculated correctly, but still, seeing 1710% is very confusing to the users. Interestingly, on the web version, the percentages are shown correctly.

**Comment by mitchdowney** [comment]
This should be in v4.16.0.

**Comment by joksas** [comment]
Thank you, Mitch, appreciate it!
