### ISSUE TITLE
Enable Chapter Art GIFs in the Android Version of Podverse

### ISSUE THREAD

**Issue by linkinparkrulz** [podverse/podverse-rn#2146]
**Is your feature request related to a problem? Please describe.**

On desktop and iOS, Chapter Art GIFs show up great and do as intended. But, on the Android version, these images don't function.

**Describe the solution you'd like**

Emulate the performance of the desktop and iOS products on the android side.

**Comment by lovegaoshi** [comment]
probably just need this:
https://github.com/lovegaoshi/azusa-player-mobile/blob/9345b33f61b2576b9923bbec76533579e9cf3b79/android/app/build.gradle#L143

**Comment by linkinparkrulz** [comment]
Wow, that would be solid if that's all that's needed.

Sent from Proton Mail mobile

-------- Original Message --------

**Comment by linkinparkrulz** [comment]
> probably just need this: https://github.com/lovegaoshi/azusa-player-mobile/blob/9345b33f61b2576b9923bbec76533579e9cf3b79/android/app/build.gradle#L143

So if you make the plugin calls  and just insert:

dependencies {

    // For animated GIF support
    implementation 'com.facebook.fresco:animated-gif:2.5.0'

    // For WebP support, including animated WebP
    implementation 'com.facebook.fresco:animated-webp:2.5.0'
    implementation 'com.facebook.fresco:webpsupport:2.5.0'

    implementation 'com.android.support:appcompat-v7:28.0.0'
    implementation 'com.android.support:support-annotations:28.0.0'
    implementation 'com.android.support:design:28.0.0'

    // The version of react-native is set by the React Native Gradle Plugin
    implementation("com.facebook.react:react-android")
    
    implementation("com.facebook.react:flipper-integration")
    if (hermesEnabled.toBoolean()) {
        implementation("com.facebook.react:hermes-android")
    } else {
        implementation jscFlavor
    }
}

in the build.gradle it should be good to go?

**Comment by lovegaoshi** [comment]
just thr animated gif one should do the trick. otherwide let me know the
episode name

**Comment by linkinparkrulz** [comment]
Yeah, i convert everything to gifs, so you're right with excluding the other stuff. 

an example you could go see on desktop or iOS would be here:

https://podverse.fm/episode/gkpNDt8zG

**Comment by linkinparkrulz** [comment]
Also @lovegaoshi is there a spot i can reach you more frequently?

**Comment by lovegaoshi** [comment]
did u try building it? with the dependency gif now works on my end. care to submit a PR?
![image](https://github.com/podverse/podverse-rn/assets/106490582/c2f990b0-417d-47e2-978a-54008516168d)
and im on PV's discord. though the other devs are at 

our primary dev channel is on Matrix and we recommend moving discussion there for the largest dev community participation https://matrix.to/#/#podverse-space:matrix.org

**Comment by linkinparkrulz** [comment]
I have not tried building it, but that's probably more so because I haven't touched android app development just websites/PWA's is my threshold atm. BUT this is awesome!!

Would you like me to submit the PR?  I would but i'm just not familiar with the github process at the moment. Happy to learn though.

**Comment by lovegaoshi** [comment]
I went ahead and did it, still would be great if you'd like to learn the process:D

**Comment by linkinparkrulz** [comment]
Nice work! Yeah I'm gonna try it out, I think I have a pull request that would work well and be an easy task to learn with.

**Comment by mitchdowney** [comment]
this should be in v4.16.0
