### ISSUE TITLE
Enable changing the global time jump forward/backward values, and the time jump values for individual podcasts

### ISSUE THREAD

**Issue by mitchdowney** [podverse/podverse-rn#458]
Currently the time jump default value is 30 seconds. The goal of this issue is to allow the user to set each of these values to any positive integer they want globally for all podcasts, and also to be able to override the time jump values for each individual podcast.

**Comment by kreonjr** [comment]
@mitchdowney #535 was closed as duplicate but I think these are separate issues. I think we should keep the separate

**Comment by mitchdowney** [comment]
Added this a while ago :)
