### ISSUE TITLE
Android Media Player cannot be dismissed when a podcast is loaded

### ISSUE THREAD

**Issue by KyleFDowney** [podverse/podverse-rn#467]
Swiping the media player will not dismiss it even when the media is paused.

https://www.androidpolice.com/2020/08/07/android-11s-new-media-player-controls-can-be-swiped-away-in-beta-3/

**Comment by mitchdowney** [comment]
I was able to dismiss the notification using 3.0.7 on an Android Pixel 4. Closing this until it's reported again.
