### ISSUE TITLE
Lock screen player buttons are randomly disabled (iOS only)

### ISSUE THREAD

**Issue by mitchdowney** [podverse/podverse-rn#492]
This issue has gone on for a long time, and appears to be related to this issue in react-native-track-player https://github.com/react-native-kit/react-native-track-player/issues/921

![image](https://user-images.githubusercontent.com/2262919/108608127-788b2c80-738a-11eb-9bd4-30b4d575defa.png)

**Comment by marf** [comment]
Hello, we have this issue too. Have you got any ideas on how to solve it? For us, some users reported that controls are all disabled randomly.

Thank you,
Marco

**Comment by mitchdowney** [comment]
@marf alas we have not found a solution yet (or an explanation even). I attempted to add the workaround [suggested here](https://github.com/react-native-kit/react-native-track-player/issues/921#issuecomment-686806847), but we're still seeing the problem.

Here's the code I tried to use:

https://github.com/podverse/podverse-rn/blob/develop/src/screens/PodcastsScreen.tsx#L174

https://github.com/podverse/podverse-rn/blob/develop/src/services/player.ts#L35

**Comment by marf** [comment]
Hi @mitchdowney , thank you for the reference!

Yeah, I have tried that but unfortunately does not work for me eighter. We tried several fixes but all of them seem not work. If you have some ideas please let us know, meanwhile we will continue to explore other solutions and if we find something working we will let you know :)

**Comment by marf** [comment]
Hey @mitchdowney have you found some solution or workaround for this issue?

Thank you!

**Comment by mitchdowney** [comment]
It seems like I have not run into this issue in quite a while...maybe the issue is fixed in react-native-track-player 1.2.6? Or in a more recent update of iOS? Going to close this issue until it is reported again.

**Comment by mitchdowney** [comment]
@marf are you still running into this issue? Are you using react-native-track-player 1.2.6?

**Comment by marf** [comment]
@mitchdowney we are still running into the issue. So in your case does everything work well?

**Comment by mitchdowney** [comment]
@marf it is hard to say for sure...I think I _have_ seen this issue in the past couple weeks, even after updating to react-native-track-player 2.x...but I haven't been able to reproduce it recently. If I see it again I'll be sure to take note...
