### ISSUE TITLE
Some Podcasts show that they are loading when "Play" is tapped but nothing happens

### ISSUE THREAD

**Issue by kreonjr** [podverse/podverse-rn#559]
Platform: Android
Example Podcasts: The spawn chunks,  the privacy, Security & OSINT Show

User comments: 

`I have been having a problem with some of my podcasts. When I tap play or pause it loads for a few seconds then stops. Nothing more happens and it is only with a few of the podcasts. Is there something I can do? I am on the newest full release and have tried adding removing the podcasts.`

Reported on 4/16/2020 via Discord

**Comment by kreonjr** [comment]
Tested on iOS on iPhone SE 2nd Edition just in case and podcast episodes seem to play fine. Might be an android only issue

**Comment by mitchdowney** [comment]
I think this is fixed in #585 and should be fixed in 3.1.0.
