### ISSUE TITLE
Allow Android to choose where downloaded episodes are saved.

### ISSUE THREAD

**Issue by kreonjr** [podverse/podverse-rn#602]
As per user request:

>`I'm a big fan of the app. Is there a way to auto-download podcasts to an SD card? I haven't seen an option to save to a card.` it would be useful to allow android users to choose where to save downloaded episodes, to allow them to use a storage with more capacity.

**Comment by mitchdowney** [comment]
Another user request:

> I installed Podverse today, and promptly filled up my 4Gb of system storage with audio files.

> Is there any way to force it to save files to the external SD card?  If so, can I move the existing files, or must they be downloaded again?

**Comment by pahlse** [comment]
bump

**Comment by 1MachineElf** [comment]
To start with, where are podcasts on Android being stored now?

**Comment by kreonjr** [comment]
Pull Request created. #879 
Option added in Download Settings to save new downloads to External Storage.

**Comment by mitchdowney** [comment]
This issue should be closed, although we have to fix #1004. I applied a fix to be released in v4.3.6 but we need to test it more.
