### ISSUE TITLE
Make all screens and features fully accessible to screen reader software

### ISSUE THREAD

**Issue by mitchdowney** [podverse/podverse-rn#705]
Test with at least VoiceOver.

**Comment by KyleFDowney** [comment]
iOS - Search Screen: Host & Podcast buttons need additional information for voice over.

**Comment by KyleFDowney** [comment]
![Screenshot_20210902-150804](https://user-images.githubusercontent.com/31670210/131916956-83d59e9d-f10d-4d28-91ab-cc2bffc0be2d.png)

`Header is read as a button, and doesn't read the header itself`
"This is the selected primary filter for this screen - button"

![Screenshot_20210902-150601](https://user-images.githubusercontent.com/31670210/131916973-093dffc1-0c58-4063-9d4a-bd7decd51e16.png)
![Screenshot_20210902-122232](https://user-images.githubusercontent.com/31670210/131916993-b6e90804-f75d-45bd-a601-256c674d5c02.png)

`Invisible selectors, crashes app when "tapped" by the screen reader`
"This is the selected sorting filter for this screen"
