### ISSUE TITLE
[Clips Page] Category filter shows 'top-past' options instead of Categories.

### ISSUE THREAD

**Issue by KyleFDowney** [podverse/podverse-rn#710]
[https://i.imgur.com/uYM7zDE.png](https://i.imgur.com/uYM7zDE.png)

When switching the filter from "top past..." to "Category", the filter options do not change to show the different categories like "Arts".

**Comment by mitchdowney** [comment]
This appears to be a problem with the staging environment data, rather than a bug with the app itself. I'm ok with just skipping Clips category tests in the mobile app for now.
