### ISSUE TITLE
option to share single episode and podcast for custom RSS feeds

### ISSUE THREAD

**Issue by stragu** [podverse/podverse-rn#757]
It would be great to add an option to share a single episode.

It could be offered in two locations:

* the ellipsis menu in the episode list
* and the ellipsis menu in the player view.

**Comment by mitchdowney** [comment]
Hello @stragu! Sorry for the delay but thanks for the feature request.

We actually do have Share buttons on both of those views.

![image](https://user-images.githubusercontent.com/2262919/133914332-326a46db-3948-48b4-96b6-70a2ad8a200a.png)

![image](https://user-images.githubusercontent.com/2262919/133914356-d9ad3143-20b3-4d59-9902-404d3946ffb7.png)

We _could_ put the Share button in the ellipsis menu on the player view, but it's already at the top of the screen, and if we put it in the ellipsis menu, then do we put all the other navigation header buttons in the ellipsis too? That could get kind of cluttered, so I'm thinking of leaving it just in the navigation header. Does that sound alright?

**Comment by stragu** [comment]
Hi @mitchdowney ! Thanks for the reply.
I think the issue is that I was looking at a podcast that didn't show these share buttons at all!

I'm wondering if it doesn't show for podcasts added from an RSS URL?

See for example this one:

https://feeds.acast.com/public/shows/c3ac5257-51e6-4ac7-8c55-16d8e61d4e4b

Gives me this in the app:

![No share button](https://user-images.githubusercontent.com/1747497/133917473-7ffdeb5b-cfdc-4d89-b733-c74939dde431.png)

However, if the same podcast "Kiffe ta race" is searched and subscribed to from the app, the share buttons are visible.

So is that a bug specific to when adding a custom RSS feed?

**Comment by mitchdowney** [comment]
@stragu ohhh, of course. Yes custom RSS feeds that are added to the app do not offer the full range of features. The biggest reason for this is a lot of custom RSS feeds are "premium" feeds that, while not password-protected, are meant for an individual paying listener, and not meant to be shared with other people. I'm not sure we have a way to support sharing custom RSS feeds without leaking paid premium feed URLs...

If your RSS feeds are meant to be publicly available (they're not private), but just aren't searchable in our database, they can be added to the Podcast Index, and then they'll be automatically added into Podverse.

Let me know if you think have any questions, or if you think it can be closed please go ahead and close it. Thanks!

**Comment by stragu** [comment]
Ah OK, that makes sense! No other question other than: could the custom RSS not be modified to make that clear to users?
For example:

> Note: **clips, playlists and sharing** are not supported for custom RSS feeds.
> To add a podcast with support for clips and playlists, use the Request Podcast link below so we can add it to our database.

**Comment by mitchdowney** [comment]
@stragu absolutely! Great idea. I went ahead and updated the helper text in this commit. It'll be in either this upcoming release or the next.

Closing the issue. Let me know if this needs anything else.

https://github.com/podverse/podverse-rn/commit/c3f7ecfacab91a58dc3f7d7fb132a12c54c5addf#diff-434395122634f503f334976454c18e6e9a440d8416c11d3a921f36eef09e6088R195

**Comment by stragu** [comment]
That's fabulous, thank you Mitch. All good I think :)
Thanks for your work!
