### ISSUE TITLE
Add "Offline mode enabled" banner on all screens when enabled

### ISSUE THREAD

**Issue by mitchdowney** [podverse/podverse-rn#759]

**Comment by kreonjr** [comment]
@mitchdowney  should this appear only when we have offline mode enabled or also when we detect that the app is offline?

**Comment by mitchdowney** [comment]
Hmm...I think we should do whenever the app is offline not just offline mode...but I don't think the app automatically handles switching into offline mode when app is offline so...seems like fixing that would be out of scope for this issue.
