### ISSUE TITLE
Add by Custom RSS podcasts are randomly disappearing (GrapheneOS only?)

### ISSUE THREAD

**Issue by mitchdowney** [podverse/podverse-rn#778]
> I am running Podverse on my Google Pixel 5 with GrapheneOS on Android 11, and I am having a problem where my paid subscription podcasts periodically disappear from my Podcasts tab and I am forced to resubscribe.

> Is this normal? I also log into the same Podverse account on an iPhone SE running iOS 14.6, and I need to manually subscribe to new shows on both devices.

**Comment by mitchdowney** [comment]
Questions I asked from the user who reported the issue, and their response:

1) Do these paid subscription podcasts require you to enter a username and password?

> One of them does and one of them does not.

2) Can you share any of the podcasts that are disappearing? And are certain podcasts disappearing more often than others?

> Making Sense with Sam Harris, Tim Dillon Subscriber Feed, and Higherside Chats Plus are the culprits. All have disappeared once or twice. Most recently, Tim Dillon and Higherside disappeared, but Sam Harris did not.

3) Are you a logged-in user on both GrapheneOS and iOS?

> Yes, I am logged in on both devices.

4) Does the "disappearing podcasts" issue also happen on iOS? Or is the problem that feeds randomly disappear on GrapheneOS, and iOS just isn't syncing with the feeds you add o GrapheneOS?

> Not sure if it has happened on iOS before, but right now my iOS Podverse subscriptions are good to go.

**Comment by Chzy2018** [comment]
I met the same problem twice, but it was not the same podcast that disappeared each time. I ran this app in my Samsung mobile phone, and sometimes when I started this app, one of my subscribed podcasts would disappear. Refreshing didn't work. After a few minutes when I started this app again, all of my subscribed podcasts were there.

And I'm not logged in this app. Maybe I need to sign up for an account?

**Comment by mitchdowney** [comment]
@Chzy2018 there were some issues with the logic handling Custom RSS podcast refreshes that I think are fixed with this PR https://github.com/podverse/podverse-rn/pull/831

I'm releasing those changes in 3.2.9 tomorrow. Hopefully this resolves the issue for you!
