### ISSUE TITLE
Make next/previous buttons skip to next or previous chapter when chapters are available

### ISSUE THREAD

**Issue by mitchdowney** [podverse/podverse-rn#780]
> Also, can we have a option for the next previous buttons to change chapters instead of queue items.

**Comment by kreonjr** [comment]
Is this something that we want it to happen automatically? If I want to actually skip to the next queue item, how to I go about doing so?

**Comment by mitchdowney** [comment]
@kreonjr I was thinking we keep it as "skip to next track" by default for non-chapters episodes, and skip chapter for chapters episodes, and long press to skip track for chapters episodes.
