### ISSUE TITLE
Alba Salix Podcast has duplicate entries (one working, one not)

### ISSUE THREAD

**Issue by kreonjr** [podverse/podverse-rn#798]
There seem to be a duplicate entry of the Alba Salix Podcast.

Bad one: https://podverse.fm/podcast/scIgd8fQ6
Good one: https://podverse.fm/podcast/pnWN3EEE6j

Perhaps old "non-wokring" version of the podcast in the database

**Comment by kreonjr** [comment]
@mitchdowney You think you can look into the bad one in our DB and if it's coming from the PI and clear it out if it isn't?

**Comment by mitchdowney** [comment]
Reported the duplicate to Dave from Podcast Index and he fixed the issue.
