### ISSUE TITLE
Sleep Timer does not work

### ISSUE THREAD

**Issue by prayforzod** [podverse/podverse-rn#816]
I am using the podverse FOSS on a graphene os android device. The sleep timer does not seem to work. The normal android version of Podverse's sleep timer also does not work on the graphene os device.

**Comment by mitchdowney** [comment]
Thanks for @prayforzod the bug report. We should have this fixed in a release this month or next.

**Comment by mitchdowney** [comment]
Alas, this has been overlooked for far too long. I'm going to pin this to the top because it really sucks that sleep timer doesn't work on Android.

**Comment by mitchdowney** [comment]
This can be fixed using the progressUpdateInterval helper that will be available in react-native-track-player v3. That interval callback should continue to run in the background even while the screen is locked.

**Comment by mitchdowney** [comment]
This is blocked by #1179
