### ISSUE TITLE
Subscriptions deleted when logging in

### ISSUE THREAD

**Issue by hunterstabler** [podverse/podverse-rn#830]
I created an account and logged in on my android, and it deleted all of my subscriptions.

In order to troubleshoot the broken search function in Podverse for Android, a Dev suggested that I try logging in. I had several subscriptions, some paid RSS feeds, and I never created an account or logged into Podverse. The search function in Podverse on my CalyxOS Pixel 4a broke at some point, but the app worked otherwise. Trying to see if the search function would work if I logged in, I created an account and logged in. Immediately all of my subscriptions were deleted and the search function is still broken, so I can't add my podcasts back other than by RSS which not all podcasts have. This is particularly frustrating because I can't get one of my paid RSS feeds to work in any app other than Podverse, but I can't add any of my other podcasts to the app now. I also tried disabling my always on VPN and tried to see if my firewall was blocking anything for Podverse, but I found nothing.

The expected behavior would be if I logged in and it didn't delete all of the podcasts that I had in my subscriptions. Also the search function would be expected to not return an error that says "Pardon the interruption. Something went wrong but we've been notified and we're on it. In the meantime, feel free to get back to listening!"

Pixel 4a unlocked
CalyxOS 2.9.0
Podverse 3.1.2

**Comment by mitchdowney** [comment]
Closing since there hasn't been a response in a while. Hopefully this issue doesn't happen again...
