### ISSUE TITLE
Lock screen controls Grey on iOS 3.3.1 1130

### ISSUE THREAD

**Issue by brianoflondon** [podverse/podverse-rn#854]
**Describe the bug**

![image](https://user-images.githubusercontent.com/28054569/139526165-e8dcb720-81a7-4814-9219-0c25e2102ac4.png)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - App Version [e.g. 22]

**Additional context**

Please feel free to [join our Discord](https://discord.gg/6HkyNKR) and chat with us in the #dev channel if you'd like to work on this.

**Comment by mitchdowney** [comment]
It looks like this might have gotten broken between react-native-track-player 2.0.0 and 2.0.3, and might be fixed in 2.2.0. We'll update the library in the next release and hopefully that fixes it. https://github.com/DoubleSymmetry/react-native-track-player/issues/1296#issuecomment-946664065

**Comment by mitchdowney** [comment]
@brianoflondon I *rarely* see this these days, although I have still seen it sometimes. It seems so rare that I don't see it being prioritized anytime soon, and any changes that would fix it would have to happen in react-native-track-player (the library we're using for audio playback). I'm going to close this unless more people report it.
