### ISSUE TITLE
Allow option of using remote-next and remote-previous buttons as time jumps in all situations

### ISSUE THREAD

**Issue by mitchdowney** [podverse/podverse-rn#861]

**Comment by brianoflondon** [comment]
I'd just say that EVEN when there are chapters, I still prefer consistent behaviour of Time Jump. For example No Agenda loads with chapters but there's just one chapter saying chapters are coming. So chapter jump is useless.

Time jump is the ONLY thing I want on a regular basis in a podcast.

**Comment by mitchdowney** [comment]
@brianoflondon ok gotcha. A few people requested the remote skip track buttons jump between chapters, and I actually like that feature myself. I'm thinking we'll put this in as an option on the Settings screen.

**Comment by mitchdowney** [comment]
Related to https://github.com/podverse/podverse-rn/issues/805

We might not even need to add a Setting if we handle skip and long-press-skip differently.

**Comment by mitchdowney** [comment]
People seem happy with the current defaults. I'm going to close this unless more people ask for different remote button behaviors.
