### ISSUE TITLE
Notification or alert when lightning balance is low

### ISSUE THREAD

**Issue by Chris869218** [podverse/podverse-rn#870]
**Is your feature request related to a problem? Please describe.**
It can be frustrating to get to the end of a long podcast and realize your wallet had been empty since the halfway point.

**Describe the solution you'd like**
Some sort of notification so I'm able to pause the podcast and top up my balance in LNPay.

**Comment by mitchdowney** [comment]
Thanks for the feature request! We definitely want to add this, but we're holding off on all V4V Lightning Network functionality until the Podcast Index "wallets and stats" service is up and running. Once that is available, V4V will be our top priority feature.

**Comment by mitchdowney** [comment]
@Chris869218 until we have V4V support on mobile, this feature won't go anywhere. Whether or not it is possible is dependent on the services we will integrate with for V4V mobile. For example, why doesn't the service we integrate with send you their own mobile notification when your balance or Podverse allowance runs low? If that service has their own mobile app, that could be possible, so where we go with this really depends on them.

I'm going to close this issue for now, but maybe we reopen it after we have V4V integrations setup.
