### ISSUE TITLE
Widescreen (iPad) support / Split mode

### ISSUE THREAD

**Issue by thomassth** [podverse/podverse-rn#889]
**Is your feature request related to a problem? Please describe.**
Things are cramped in a small screen. Very hard to use on an iPad. 

**Describe the solution you'd like**
Proper iPad support
Split screen support

**Additional context**
Allow contents to be stretched, as a stopgap solution before building proper wide screen UI

**Comment by mitchdowney** [comment]
Hi @thomassth, just to confirm, do you see this issue when you use the mobile app on an iPad? Or when you use the website from an iPad?

If it's for the website, then the repo for that issue would actually be here https://github.com/podverse/podverse-web/issues

Also if you have a chance a screenshot would be nice.

**Comment by thomassth** [comment]
The app one, from app store

And I think it's quite simple as an issue, when you open the app in iPad, it goes into iPhone app mode, with limited screen space, bad keyboard experience etc.

The hard part is applying the wide screen UI, but since the web version has that, maybe it's trivial too.

**Comment by mitchdowney** [comment]
@thomassth ohh ok, gotcha. I forgot we even allowed the app to be downloaded on iPad. Kind of a questionable decision when the UX is so bad with the mobile sized screen...we'd like to add proper iPad support, but we have so many high priority items to work on right now, I don't know when we'll get to making the app compatible with iPad.

If anyone wants to jump in and help style the app for iPad before we get to it, contributions would be greatly appreciated.

**Comment by thomassth** [comment]
We can allow iPads to stretch iPhone views for now as a stop-gap solution.

It may look a bit ugly but it would be more functional.

While you're at it please also enable split screen mode for iPads. It would only use a narrow part of the screen (iphone-like but taller) thus almost no new UI is needed. And it's the most useful form IMO.

**Comment by suorcd** [comment]
On iPad OS 16 stage manager does this ok ![image](https://user-images.githubusercontent.com/60907848/199360347-486998bf-16f8-4e0f-bb60-d49d26525ebc.png)

**Comment by suorcd** [comment]
It would still be nice to have split view enabled.

**Comment by mitchdowney** [comment]
Interesting I'm not familiar with Stage Manager. Is that the "run iOS apps on M1 laptops" software?

Tablet support would be great. We'd definitely like to do it. I'm not familiar with the work involved though, both in enabling tablet mode for iOS and Android, and also any different distribution steps that may be needed. I'm going to add the "help wanted" label in case it's a project other developers would be interested in.

**Comment by suorcd** [comment]
Stage manager is trying to allow multi-app work flows. in the pic above it is allowing Podverse to be a floating window over Safari

**Comment by mitchdowney** [comment]
@thomassth @suorcd this should be in v4.7.0. That is now available in Beta for iPad if anyone wants to test it: https://testflight.apple.com/join/VpxVTOsT

https://github.com/podverse/podverse-rn/issues/1215
