### ISSUE TITLE
How does Podverse create and share clips?

### ISSUE THREAD

**Issue by GoutamVerma** [podverse/podverse-rn#960]
Hello Podverse team!

I want to know how does podverse makes a clip from the podcast. And what approach and libraries they use to create a clip?

**Comment by GoutamVerma** [comment]
@mitchdowney

**Comment by mitchdowney** [comment]
@GoutamVerma The approach we use for creating and sharing clips is relatively simple. When a user "creates a clip" all we do is save the clip's start time, end time, and title to our database. Then when a user plays a "clip", we load the whole episode in the player, and then jump the player ahead to the clip's start time, and set a listener to stop the player after the end time of the clip is reached. There are pros and cons to this approach...another common approach is developers chop up the audio file for the clip and host it on their servers. Let me know if you have any more questions!
