### ISSUE TITLE
Can't delete account from More > Settings > Account screen

### ISSUE THREAD

**Issue by mitchdowney** [podverse/podverse-rn#998]

**Comment by mitchdowney** [comment]
This is _partially_ fixed. The account can now be deleted in 4.3.4, but there is buggy behavior because the user is not logged-out when their account is deleted.

TODO: sign out the user after their account is deleted. Make sure there isn't a race condition either.

**Comment by kreonjr** [comment]
> This is _partially_ fixed. The account can now be deleted in 4.3.4, but there is buggy behavior because the user is not logged-out when their account is deleted.
> 
> TODO: sign out the user after their account is deleted. Make sure there isn't a race condition either.

Maybe this should be done in the backend and the delete account response block just makes sure to clear any local state instead of making a logout call. Thoughts?

**Comment by mitchdowney** [comment]
@kreonjr I think I misidentified the issue...the problem is that after deleting your account, the screen doesn't navigate backwards out of SettingsAccountScreen.tsx. If it did, we would see the user has been logged out and the Account row in SettingsScreen is no longer available.

**Comment by mitchdowney** [comment]
A fix for this should be in v4.2.6.
